import { createContext, useContext, useState, useEffect, useCallback, ReactNode, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translateText: (text: string) => Promise<string>;
  translateBatch: (texts: string[]) => Promise<Record<string, string>>;
  isTranslating: boolean;
}

// Default Vietnamese translations (source)
const viTranslations: Record<string, string> = {
  // Navigation
  home: 'Trang chủ',
  products: 'Sản phẩm',
  cart: 'Giỏ hàng',
  login: 'Đăng nhập',
  logout: 'Đăng xuất',
  profile: 'Tài khoản',
  search: 'Tìm kiếm',
  wishlist: 'Yêu thích',
  notifications: 'Thông báo',
  settings: 'Cài đặt',
  
  // Actions
  addToCart: 'Thêm vào giỏ',
  buyNow: 'Mua ngay',
  viewAll: 'Xem tất cả',
  viewMore: 'Xem thêm',
  viewNow: 'Xem ngay',
  collapse: 'Thu gọn',
  save: 'Lưu',
  cancel: 'Hủy',
  confirm: 'Xác nhận',
  delete: 'Xóa',
  edit: 'Sửa',
  create: 'Tạo',
  add: 'Thêm',
  apply: 'Áp dụng',
  remove: 'Xóa bỏ',
  close: 'Đóng',
  back: 'Quay lại',
  next: 'Tiếp theo',
  previous: 'Trước',
  submit: 'Gửi',
  refresh: 'Làm mới',
  copy: 'Sao chép',
  copied: 'Đã sao chép',
  continueShopping: 'Tiếp tục mua sắm',
  proceedToCheckout: 'Tiến hành thanh toán',
  processing: 'Đang xử lý...',
  saveChanges: 'Lưu thay đổi',
  saving: 'Đang lưu...',
  changeBanner: 'Đổi banner',
  exploreProducts: 'Khám phá sản phẩm',
  enter: 'Nhập',
  continue: 'Tiếp tục',
  goBack: 'Quay lại',
  submitRegister: 'Gửi đăng ký',
  enterDashboard: 'Vào Dashboard',
  requestReward: 'Yêu cầu đổi thưởng',
  
  // Features
  flashSale: 'Flash Sale',
  event: 'Sự kiện',
  support: 'Hỗ trợ',
  news: 'Tin tức',
  referral: 'Giới thiệu',
  orderLookup: 'Tra cứu đơn hàng',
  endsIn: 'Kết thúc sau',
  soldOut: 'Hết hàng',
  remaining: 'Còn',
  viewAllProducts: 'Xem tất cả {count} sản phẩm',
  
  // Event Page
  noEventsYet: 'Chưa có sự kiện nào',
  noEventsRunning: 'Hiện tại không có sự kiện nào đang diễn ra',
  goHome: 'Về trang chủ',
  onGoing: 'Đang diễn ra',
  currentPoints: 'Điểm hiện có',
  noSpinHistory: 'Chưa có lịch sử quay',
  spinResult: 'Kết quả quay',
  pleaseLoginToSpin: 'Vui lòng đăng nhập để quay',
  notEnoughPoints: 'Không đủ điểm để quay',
  spinError: 'Có lỗi xảy ra khi quay',
  claimRewardSuccess: 'Nhận thưởng thành công!',
  claimReward: 'Nhận thưởng',
  fillInfoToClaimReward: 'Vui lòng điền thông tin để nhận thưởng:',
  confirmClaimReward: 'Xác nhận nhận thưởng',
  premiumProduct: 'Sản phẩm Premium',
  topUpGame: 'Nạp game',
  
  // Compare Page
  noProductsToCompare: 'Chưa có sản phẩm để so sánh',
  addProductsToCompare: 'Thêm sản phẩm vào danh sách so sánh từ trang danh mục',
  compareProducts: 'So sánh sản phẩm',
  productsCount: '{count} sản phẩm',
  clearAllProducts: 'Xóa tất cả',
  allProducts: 'Tất cả sản phẩm',
  attribute: 'Thuộc tính',
  contactForPrice: 'Liên hệ',
  backToShopping: 'Quay lại mua sắm',
  
  // Product Pages
  searchProducts: 'Tìm kiếm sản phẩm...',
  searchFastTopup: 'Tìm kiếm và nạp game nhanh chóng',
  explorePremium: 'Khám phá các sản phẩm và dịch vụ premium',
  type: 'Loại',
  all: 'Tất cả',
  allCategories: 'Tất cả danh mục',
  sort: 'Sắp xếp',
  newest: 'Mới nhất',
  oldest: 'Cũ nhất',
  nameAZ: 'Tên A-Z',
  nameZA: 'Tên Z-A',
  filters: 'Bộ lọc',
  clearFilters: 'Xóa bộ lọc',
  noProductsFound: 'Không tìm thấy sản phẩm nào',
  noProductsMatchFilter: 'Không có sản phẩm nào phù hợp với bộ lọc',
  showingProducts: 'Hiển thị',
  ofProducts: 'sản phẩm',
  totalProducts: 'tổng',
  
  // Item Shop Page
  noAvatarFrames: 'Chưa có khung avatar nào',
  giftAvatarFrame: 'Tặng khung Avatar',
  buyAvatarFrame: 'Mua khung Avatar',
  chooseGiftRecipient: 'Chọn người bạn muốn tặng',
  confirmBuyFrame: 'Xác nhận mua khung avatar này?',
  pleaseLoginToSendImage: 'Vui lòng đăng nhập để gửi ảnh',
  pleaseLoginToChat: 'Vui lòng đăng nhập để chat',
  
  // Categories
  premiumAccounts: 'Premium',
  gameAccounts: 'Account',
  topUp: 'Topup',
  
  // Product
  price: 'Giá',
  originalPrice: 'Giá gốc',
  discount: 'Giảm giá',
  inStock: 'Còn hàng',
  outOfStock: 'Hết hàng',
  description: 'Mô tả',
  warranty: 'Bảo hành',
  usageGuide: 'Hướng dẫn sử dụng',
  guide: 'Hướng dẫn',
  reviews: 'Đánh giá',
  relatedProducts: 'Sản phẩm liên quan',
  selectPackage: 'Chọn gói',
  quantity: 'Số lượng',
  sold: 'Đã bán',
  available: 'Còn lại',
  package: 'Gói',
  productCode: 'Mã sản phẩm',
  category: 'Thể loại',
  status: 'Tình trạng',
  postedTime: 'Thời gian đăng',
  sellingPrice: 'Giá bán',
  accountInfo: 'Thông tin về tài khoản',
  applyPromoCode: 'Áp dụng mã khuyến mãi',
  enterDiscountCode: 'Nhập mã giảm giá',
  customerBenefits: 'Quyền lợi khách hàng',
  instantDelivery: 'Tài khoản được cung cấp ngay sau khi thanh toán thành công.',
  refundGuarantee: 'Đảm bảo hoàn tiền 100% nếu tài khoản có vấn đề.',
  sellerSupport: 'Người bán hỗ trợ và bảo hành trong quá trình giao dịch.',
  recordAdvice: 'Khuyến khích: Thực hiện quay video từ lúc mua tài khoản để đảm bảo an toàn và có bằng chứng rõ ràng khi xảy ra tranh chấp!',
  recommendedProducts: 'Sản phẩm đề xuất',
  buyAccount: 'Mua tài khoản',
  emailToReceiveAccount: 'Email nhận tài khoản',
  vipDiscountLabel: 'Giảm VIP',
  taxLabel: 'Thuế',
  loginToPayWithBalance: 'Đăng nhập để thanh toán bằng số dư',
  usagePeriod: 'Thời hạn sử dụng',
  enterAdditionalInfo: 'Nhập thông tin bổ sung',
  orderInfo: 'Thông tin đơn hàng',
  allPackagesOutOfStock: 'Tất cả các gói hiện đang hết hàng. Vui lòng quay lại sau.',
  quickPayment: 'Thanh toán nhanh',
  emailToReceive: 'Email nhận hàng',
  productNotFound: 'Sản phẩm không tồn tại',
  productMayDeleted: 'Sản phẩm này có thể đã bị xóa.',
  returnToHome: 'Quay về trang chủ',
  addedToCart: 'Đã thêm vào giỏ hàng',
  pleaseSelectPackage: 'Vui lòng chọn một gói sản phẩm',
  pleaseEnter: 'Vui lòng nhập',
  pleaseEnterEmail: 'Vui lòng nhập email để nhận sản phẩm',
  payWithBalanceBtn: 'Thanh toán bằng số dư',
  payWithPayOSBtn: 'Thanh toán với PayOS',
  accountsRemaining: 'Còn {count} acc',
  addedToWishlistWithNotify: 'Đã thêm vào yêu thích và bật thông báo giảm giá',
  pleaseLoginForNotify: 'Vui lòng đăng nhập để nhận thông báo',
  pleaseLoginToBuy: 'Vui lòng đăng nhập để mua hàng',
  addToWishlistFirst: 'Vui lòng thêm vào yêu thích trước khi bật thông báo',
  turnOffSaleNotify: 'Tắt thông báo giảm giá',
  turnOnSaleNotify: 'Bật thông báo khi có giảm giá',
  productReviews: 'Đánh giá sản phẩm',
  productLabel: 'Sản phẩm',
  outOfStockShort: 'Hết',
  
  // Cart & Checkout
  emptyCart: 'Giỏ hàng trống',
  emptyCartMessage: 'Bạn chưa có sản phẩm nào trong giỏ hàng. Hãy khám phá các sản phẩm của chúng tôi.',
  subtotal: 'Tạm tính',
  total: 'Tổng cộng',
  totalPayment: 'Tổng thanh toán',
  checkout: 'Thanh toán',
  voucherCode: 'Mã giảm giá',
  referralCode: 'Mã giới thiệu',
  paymentMethod: 'Phương thức thanh toán',
  balance: 'Số dư',
  payWithBalance: 'Thanh toán bằng số dư',
  payWithPayOS: 'Thanh toán qua PayOS',
  insufficientBalance: 'Số dư không đủ',
  orderSummary: 'Tóm tắt đơn hàng',
  orderDetails: 'Chi tiết đơn hàng',
  tax: 'Thuế',
  vipDiscount: 'Giảm giá VIP',
  voucherDiscount: 'Giảm voucher',
  buyerInfo: 'Thông tin người mua',
  referralCommissionNote: 'Người giới thiệu sẽ nhận hoa hồng khi đơn hàng hoàn tất',
  enterReferralCode: 'Nhập mã giới thiệu (nếu có)',
  enterVoucherCode: 'Nhập mã giảm giá',
  voucherApplied: 'Đã áp dụng mã',
  securePayment: 'Thanh toán an toàn với SSL 256-bit',
  payOSDescription: 'Chuyển khoản ngân hàng, QR Pay, Ví điện tử',
  currentBalance: 'Số dư hiện tại',
  notEnoughBalance: 'Không đủ số dư',
  topUpMore: 'Nạp thêm',
  cartItemCount: 'Giỏ hàng',
  needProductFirst: 'Bạn cần thêm sản phẩm vào giỏ hàng trước',
  returnHome: 'Quay lại trang chủ',
  appliedVouchers: 'Mã giảm giá đã áp dụng',
  manageVouchersInCart: 'Quản lý mã giảm giá trong',
  paypalPayment: 'Thanh toán PayPal',
  internationalPayment: 'Thanh toán quốc tế',
  paymentSuccess: 'Thanh toán thành công',
  orderSuccess: 'Đặt hàng thành công',
  orderError: 'Đặt hàng thất bại',
  paymentFailed: 'Thanh toán thất bại',
  articleNotFound: 'Không tìm thấy bài viết',
  byAuthor: 'Bởi',
  
  // Auth
  email: 'Email',
  password: 'Mật khẩu',
  confirmPassword: 'Xác nhận mật khẩu',
  fullName: 'Họ tên',
  signUp: 'Đăng ký',
  signIn: 'Đăng nhập',
  forgotPassword: 'Quên mật khẩu?',
  orContinueWith: 'hoặc',
  resetPassword: 'Đặt lại mật khẩu',
  sendOTP: 'Gửi mã OTP',
  verifyOTP: 'Xác nhận OTP',
  account: 'Tài khoản',
  loginOrSignup: 'Đăng nhập hoặc đăng ký để tiếp tục',
  loginWithGoogle: 'Đăng nhập với Google',
  loginWithDiscord: 'Đăng nhập với Discord',
  loggingIn: 'Đang đăng nhập...',
  signingUp: 'Đang đăng ký...',
  loginSuccess: 'Đăng nhập thành công',
  signupSuccess: 'Đăng ký thành công! Đang đăng nhập...',
  emailInvalid: 'Email không hợp lệ',
  passwordMinLength: 'Mật khẩu phải có ít nhất 6 ký tự',
  fullNameMinLength: 'Họ tên phải có ít nhất 2 ký tự',
  loginToContinue: 'Đăng nhập để tiếp tục',
  pleaseLoginToViewOrders: 'Vui lòng đăng nhập để xem lịch sử đơn hàng của bạn.',
  pleaseLoginToJoinReferral: 'Vui lòng đăng nhập để tham gia chương trình giới thiệu và theo dõi hoa hồng của bạn.',
  
  // Profile
  myOrders: 'Đơn hàng của tôi',
  myWishlist: 'Danh sách yêu thích',
  security: 'Bảo mật',
  depositHistory: 'Lịch sử nạp tiền',
  vipLevel: 'Cấp VIP',
  totalSpent: 'Tổng chi tiêu',
  accountInfoProfile: 'Thông tin tài khoản',
  personalInfo: 'Thông tin cá nhân',
  changePassword: 'Đổi mật khẩu',
  twoFactorAuth: '2FA',
  loginHistory: 'Lịch sử đăng nhập',
  vouchers: 'Voucher',
  yourVouchers: 'Voucher của bạn',
  systemVouchers: 'Voucher hệ thống',
  availableVouchers: 'Voucher có sẵn',
  noVouchersAvailable: 'Không có voucher nào',
  avatarFrames: 'Khung avatar',
  deposit: 'Nạp tiền',
  depositToAccount: 'Nạp tiền vào tài khoản',
  selectOrEnterAmount: 'Chọn số tiền hoặc nhập số tiền muốn nạp',
  orEnterOtherAmount: 'Hoặc nhập số tiền khác',
  enterAmount: 'Nhập số tiền...',
  minimumDeposit: 'Tối thiểu:',
  paypalNotConfigured: 'PayPal chưa được cấu hình. Vui lòng chuyển sang VND hoặc liên hệ hỗ trợ.',
  depositViaPayOS: 'Nạp tiền qua PayOS',
  depositViaPayPal: 'Nạp tiền qua PayPal',
  depositViaPayPalDesc: 'Nạp tiền qua PayPal (USD)',
  depositPayPalNote: 'Số tiền sẽ được chuyển đổi sang USD để thanh toán qua PayPal',
  depositCancelled: 'Đã hủy nạp tiền',
  depositSuccess: 'Nạp tiền thành công!',
  viewDepositHistory: 'Xem lịch sử các giao dịch nạp tiền',
  noDepositYet: 'Chưa có giao dịch nạp tiền nào',
  viewOrderHistory: 'Xem lịch sử mua hàng',
  noOrderYet: 'Chưa có đơn hàng nào',
  wishlistDescription: 'Theo dõi sản phẩm yêu thích và nhận thông báo khi có giảm giá',
  noWishlistYet: 'Chưa có sản phẩm yêu thích',
  notifyOnDiscount: 'Thông báo giảm giá',
  updateAccountInfo: 'Cập nhật thông tin tài khoản của bạn',
  phone: 'Số điện thoại',
  enterFullName: 'Nhập họ tên...',
  enterPhone: 'Nhập số điện thoại...',
  accountBalance: 'Số dư tài khoản',
  remainingToNextVip: 'Còn',
  toReach: 'đạt',
  history: 'Lịch sử',
  orders: 'Đơn hàng',
  frames: 'Khung',
  api: 'API',
  fileTooLarge: 'File quá lớn',
  maxFileSize: 'Tối đa',
  minDepositAmount: 'Số tiền nạp tối thiểu',
  cannotCreatePaymentLink: 'Không thể tạo link thanh toán',
  depositError: 'Có lỗi xảy ra khi nạp tiền',
  updateSuccess: 'Cập nhật thông tin thành công',
  updateError: 'Có lỗi xảy ra khi cập nhật thông tin',
  logoutSuccess: 'Đã đăng xuất',
  
  // Ticket & Support
  ticketNotFound: 'Không tìm thấy ticket.',
  needLoginToViewTicket: 'Bạn cần đăng nhập để xem ticket.',
  backToList: 'Quay lại danh sách',
  ticketClosed: 'Ticket này đã được đóng. Tạo ticket mới nếu bạn cần hỗ trợ thêm.',
  enterMessage: 'Nhập tin nhắn...',
  ticketStatusOpen: 'Mở',
  ticketStatusPending: 'Chờ xử lý',
  ticketStatusResolved: 'Đã giải quyết',
  ticketStatusClosed: 'Đã đóng',
  categoryGeneral: 'Câu hỏi chung',
  categoryOrder: 'Vấn đề đơn hàng',
  categoryPayment: 'Thanh toán',
  categoryAccount: 'Tài khoản',
  categoryTechnical: 'Kỹ thuật',
  categoryOther: 'Khác',
  categoryLabel: 'Danh mục',
  createdLabel: 'Tạo',
  
  // Shop Support (Marketplace)
  shopSupport: 'Hỗ trợ Shop',
  shopSupportDesc: 'Các cuộc hội thoại với shop trên Marketplace',
  noShopTickets: 'Bạn chưa có cuộc hội thoại nào với shop',
  
  // Support Page Tabs
  allTickets: 'Tất cả',
  systemTickets: 'Hệ thống',
  shopTickets: 'Shop',
  systemLabel: 'Hệ thống',
  noSystemTickets: 'Chưa có ticket hệ thống',
  noSystemTicketsDesc: 'Tạo ticket để được hỗ trợ từ đội ngũ quản trị',
  createNewTicket: 'Tạo ticket mới',
  manageSupportRequests: 'Quản lý các yêu cầu hỗ trợ của bạn',
  typeMessage: 'Nhập tin nhắn...',
  you: 'Bạn',
  contactShop: 'Liên hệ Shop',
  contactShopDesc: 'Gửi tin nhắn cho shop để được hỗ trợ',
  messageSubject: 'Tiêu đề',
  messageContent: 'Nội dung tin nhắn',
  relatedOrder: 'Đơn hàng liên quan (tuỳ chọn)',
  noOrdersFromShop: 'Bạn chưa có đơn hàng nào từ shop này',
  sendMessage: 'Gửi tin nhắn',
  messageSent: 'Đã gửi tin nhắn',
  messageError: 'Không thể gửi tin nhắn',
  inviteAdmin: 'Mời Admin hỗ trợ',
  adminInvited: 'Đã mời Admin tham gia hỗ trợ',
  resolveTicket: 'Đánh dấu đã giải quyết',
  ticketResolved: 'Đã đánh dấu ticket đã giải quyết',
  
  
  // News
  articleNotFound: 'Không tìm thấy bài viết',
  byAuthor: 'bởi',
  
  // Order Status
  pending: 'Chờ xử lý',
  processingStatus: 'Đang xử lý',
  completed: 'Hoàn thành',
  cancelled: 'Đã hủy',
  delivered: 'Đã giao',
  refunded: 'Đã hoàn tiền',
  paid: 'Đã thanh toán',
  waitingDelivery: 'Chờ giao hàng',
  pendingPayment: 'Chờ thanh toán',
  draft: 'Nháp',
  statusSuccess: 'Thành công',
  statusPending: 'Đang xử lý',
  statusFailed: 'Thất bại',
  paymentFailed: 'Thanh toán thất bại',
  expired: 'Hết hạn',
  
  // Messages
  success: 'Thành công',
  error: 'Lỗi',
  loading: 'Đang tải...',
  noData: 'Không có dữ liệu',
  pleaseLogin: 'Vui lòng đăng nhập',
  pleaseLoginToContinue: 'Bạn cần đăng nhập để tiếp tục thanh toán',
  pleaseLoginToView: 'Bạn cần đăng nhập để xem giỏ hàng và thanh toán',
  loginNow: 'Đăng nhập ngay',
  noResults: 'Không tìm thấy kết quả',
  confirmDelete: 'Bạn có chắc muốn xóa?',
  actionSuccess: 'Thực hiện thành công',
  actionFailed: 'Thực hiện thất bại',
  paymentSuccess: 'Thanh toán thành công!',
  paymentError: 'Có lỗi xảy ra khi thanh toán',
  orderSuccess: 'Đặt hàng thành công! Đang chuyển đến thanh toán...',
  orderError: 'Có lỗi xảy ra khi đặt hàng',
  pleaseEnterVoucher: 'Vui lòng nhập mã giảm giá',
  voucherNotFound: 'Mã giảm giá không tồn tại hoặc đã hết hạn',
  voucherExpired: 'Mã giảm giá đã hết hạn',
  voucherUsedUp: 'Mã giảm giá đã hết lượt sử dụng',
  minOrderValue: 'Đơn hàng tối thiểu',
  voucherApplySuccess: 'Áp dụng mã giảm giá thành công',
  pleaseLoginToPay: 'Vui lòng đăng nhập để thanh toán',
  lookupError: 'Có lỗi xảy ra khi tra cứu',
  registerError: 'Có lỗi xảy ra khi đăng ký',
  verifySuccess: 'Xác thực thành công',
  emailAlreadyRegistered: 'Email này đã được đăng ký',
  registerSuccess: 'Đăng ký thành công! Vui lòng chờ admin duyệt.',
  noReferralCode: 'Chưa có mã giới thiệu. Vui lòng liên hệ admin.',
  emailNotApproved: 'Email chưa được duyệt tham gia chương trình',
  codeUpdateError: 'Không thể cập nhật mã',
  codeInUse: 'Mã này đã được sử dụng',
  codeMinLength: 'Mã giới thiệu phải có ít nhất 4 ký tự',
  noCreditsToRedeem: 'Bạn chưa có hoa hồng để đổi thưởng',
  rewardRequestSent: 'Đã gửi yêu cầu đổi thưởng. Admin sẽ xử lý trong 24h.',
  rewardRequestError: 'Không thể gửi yêu cầu',
  copiedReferralCode: 'Đã sao chép mã giới thiệu',
  codeUpdated: 'Đã cập nhật mã',
  
  // Time
  today: 'Hôm nay',
  yesterday: 'Hôm qua',
  thisWeek: 'Tuần này',
  thisMonth: 'Tháng này',
  daysAgo: 'ngày trước',
  hoursAgo: 'giờ trước',
  minutesAgo: 'phút trước',
  justNow: 'Vừa xong',
  
  // Theme
  lightMode: 'Chế độ sáng',
  darkMode: 'Chế độ tối',
  language: 'Ngôn ngữ',
  
  // Footer
  aboutUs: 'Về chúng tôi',
  contact: 'Liên hệ',
  terms: 'Điều khoản',
  privacy: 'Chính sách bảo mật',
  links: 'Liên kết',
  supportTicket: 'Ticket hỗ trợ',
  hotline: 'Hotline',
  loginToUseSupport: 'Đăng nhập để sử dụng hỗ trợ',
  loginToUseSupportDesc: 'Bạn cần đăng nhập để tạo ticket hỗ trợ và xem lịch sử hỗ trợ của mình.',
  allRightsReserved: 'Đã đăng ký bản quyền',
  platformDescription: 'Nền tảng mua bán sản phẩm số uy tín. Thanh toán an toàn, giao hàng tức thì.',
  
  // Wishlist & Notifications
  addToWishlist: 'Thêm vào yêu thích',
  removeFromWishlist: 'Xóa khỏi yêu thích',
  notifyOnSale: 'Thông báo khi giảm giá',
  turnOnNotifications: 'Bật thông báo',
  turnOffNotifications: 'Tắt thông báo',
  
  // Homepage
  featuredProducts: 'Sản phẩm nổi bật',
  featuredProductsDesc: 'Danh sách những sản phẩm theo xu hướng',
  latestNews: 'Tin tức mới nhất',
  quickActions: 'Truy cập nhanh',
  categories: 'Danh mục',
  gameAccountsDesc: 'Tài khoản game uy tín, giá tốt nhất',
  topUpDesc: 'Nạp nhanh, uy tín, giá tốt',
  designServices: 'Dịch vụ thiết kế',
  designServicesDesc: 'Dịch vụ thiết kế chuyên nghiệp từ các designer',
  viewServices: 'Xem dịch vụ',
  addProductsInAdmin: 'Thêm sản phẩm trong Admin',
  referralCTAPrefix: 'Nhận hoa hồng',
  referralCTASuffix: 'cho mỗi đơn hàng từ bạn bè.',
  joinNow: 'Tham gia ngay',
  specialOffers: 'Ưu đãi đặc biệt',
  useCode: 'Sử dụng mã',
  toGet: 'để',
  discountAwaiting: 'Nhiều mã giảm giá hấp dẫn đang chờ bạn khám phá.',
  changingLanguage: 'Đang chuyển ngôn ngữ...',
  
  // News
  newsAndPromos: 'Tin tức & Khuyến mãi',
  noArticlesYet: 'Chưa có bài viết nào',
  by: 'bởi',
  
  // Filter & Sort
  filter: 'Lọc',
  sort: 'Sắp xếp',
  sortNewest: 'Mới nhất',
  sortOldest: 'Cũ nhất',
  sortPriceHigh: 'Giá cao → thấp',
  sortPriceLow: 'Giá thấp → cao',
  priceRange: 'Khoảng giá',
  allCategories: 'Tất cả danh mục',
  filters: 'Bộ lọc',
  highestPrice: 'Giá cao nhất',
  lowestPrice: 'Giá thấp nhất',
  allStatus: 'Tất cả trạng thái',
  fromDate: 'Từ ngày',
  toDate: 'Đến ngày',
  selectDate: 'Chọn ngày',
  clearFilters: 'Xóa bộ lọc',
  searchOrderProduct: 'Tìm theo mã đơn, tên sản phẩm...',
  showingOrders: 'Hiển thị',
  ofOrders: 'đơn hàng',
  totalOrders: 'tổng',
  noOrdersFound: 'Không có đơn hàng nào',
  noOrdersMatchFilter: 'Không tìm thấy đơn hàng phù hợp với bộ lọc',
  
  // Tickets (additional)
  createTicket: 'Tạo ticket',
  ticketSubject: 'Tiêu đề',
  ticketDescription: 'Mô tả vấn đề',
  ticketStatus: 'Trạng thái',
  reply: 'Trả lời',
  
  // Admin
  admin: 'Quản trị',
  dashboard: 'Tổng quan',
  manageUsers: 'Quản lý người dùng',
  manageOrders: 'Quản lý đơn hàng',
  manageProducts: 'Quản lý sản phẩm',
  manageVouchers: 'Quản lý voucher',
  systemSettings: 'Cài đặt hệ thống',
  
  // User Management
  banUser: 'Khóa tài khoản',
  unbanUser: 'Mở khóa tài khoản',
  userBanned: 'Tài khoản đã bị khóa',
  userActive: 'Đang hoạt động',
  sendNotification: 'Gửi thông báo',
  viewOrders: 'Xem đơn hàng',
  adjustBalance: 'Điều chỉnh số dư',
  
  // Reviews
  writeReview: 'Viết đánh giá',
  updateYourReview: 'Cập nhật đánh giá của bạn',
  selectStars: 'Chọn số sao',
  commentOptional: 'Nhận xét (không bắt buộc)',
  shareExperience: 'Chia sẻ trải nghiệm của bạn...',
  update: 'Cập nhật',
  sendReview: 'Gửi đánh giá',
  reviewCount: 'đánh giá',
  verifiedPurchase: 'Đã mua hàng',
  adminReply: 'Phản hồi từ Admin',
  anonymous: 'Ẩn danh',
  noReviewsYet: 'Chưa có đánh giá nào. Hãy là người đầu tiên đánh giá!',
  loginToReview: 'Đăng nhập để viết đánh giá',
  pleaseSelectStars: 'Vui lòng chọn số sao',
  reviewUpdated: 'Cập nhật đánh giá thành công',
  reviewSubmitted: 'Đánh giá thành công',
  reviewError: 'Có lỗi xảy ra',
  submitting: 'Đang gửi...',
  
  // Order Lookup Page
  yourOrders: 'Đơn hàng của bạn',
  viewAllYourOrders: 'Xem tất cả đơn hàng của bạn',
  ordersOf: 'Đơn hàng của',
  includingTax: 'Đã bao gồm thuế',
  deliveryContent: 'Nội dung giao hàng:',
  viewDetailedInvoice: 'Xem hóa đơn chi tiết',
  
  // Referral Page
  referralProgram: 'Chương trình giới thiệu',
  referAndEarn: 'Giới thiệu bạn bè và nhận hoa hồng lên đến',
  howItWorks: 'Cách thức hoạt động',
  joinReferral: 'Đăng ký tham gia',
  fillInfoAndWait: 'Điền thông tin và chờ admin duyệt',
  getReferralCode: 'Nhận mã giới thiệu',
  afterApprovalGetCode: 'Sau khi được duyệt, bạn sẽ có mã riêng',
  getReward: 'Nhận thưởng',
  accumulateCommission: 'Tích lũy hoa hồng và đổi thành voucher',
  checkStatus: 'Kiểm tra trạng thái',
  enterEmailToCheck: 'Nhập email để kiểm tra trạng thái đăng ký hoặc đăng ký mới',
  fullNameRequired: 'Họ và tên *',
  emailRequired: 'Email *',
  noteOptional: 'Ghi chú (nếu có)',
  reasonToJoin: 'Lý do muốn tham gia...',
  pendingApproval: 'Đang chờ duyệt',
  requestUnderReview: 'Yêu cầu của bạn đang được admin xem xét. Vui lòng quay lại sau.',
  nameLabel: 'Họ tên:',
  emailLabel: 'Email:',
  registerDateLabel: 'Ngày đăng ký:',
  requestRejected: 'Yêu cầu bị từ chối',
  sorryRequestRejected: 'Rất tiếc, yêu cầu tham gia của bạn đã bị từ chối.',
  reasonLabel: 'Lý do:',
  accountApproved: 'Tài khoản đã được duyệt',
  verifyToEnterDashboard: 'Xác thực để vào dashboard',
  loggedInAs: 'Đang đăng nhập với',
  totalReferrals: 'Số người giới thiệu',
  totalCommission: 'Tổng hoa hồng',
  availableCommission: 'Hoa hồng khả dụng',
  yourReferralCode: 'Mã giới thiệu của bạn',
  shareCodeToEarn: 'Chia sẻ mã này cho bạn bè để nhận hoa hồng khi họ mua hàng',
  redeemReward: 'Đổi thưởng',
  redeemCommissionToVoucher: 'Đổi hoa hồng thành voucher giảm giá',
  minimum: 'tối thiểu',
  transactionHistory: 'Lịch sử giao dịch',
  noTransactionsYet: 'Chưa có giao dịch nào',
  
  // SMM Panel
  smmPanel: 'SMM Panel',
  smmServices: 'Danh sách dịch vụ SMM',
  smmServicesDesc: 'Tăng tương tác mạng xã hội nhanh chóng',
  smmOrder: 'Đặt đơn SMM',
  smmOrderDesc: 'Chọn dịch vụ và nhập thông tin để đặt đơn',
  smmOrders: 'Đơn hàng SMM',
  smmOrdersDesc: 'Theo dõi trạng thái đơn hàng của bạn',
  smmBulkOrder: 'Đặt đơn số lượng lớn',
  smmBulkOrderDesc: 'Đặt nhiều đơn cùng lúc bằng định dạng: service_id|link|quantity',
  smmOrderInfo: 'Thông tin đơn hàng',
  smmPlatform: 'Nền tảng',
  smmServiceType: 'Loại dịch vụ',
  smmServicePackage: 'Gói dịch vụ',
  smmSelectPlatform: 'Chọn nền tảng',
  smmSelectServiceType: 'Chọn loại dịch vụ',
  smmSelectPackage: 'Chọn gói',
  smmAllPlatforms: 'Tất cả nền tảng',
  smmAllServiceTypes: 'Tất cả loại dịch vụ',
  smmLink: 'Link',
  smmEnterUrl: 'Nhập URL',
  smmQuantity: 'Số lượng',
  smmIncreased: 'Đã tăng',
  smmQuantityRange: 'Số lượng phải từ {min} đến {max}',
  smmPrice: 'Giá',
  smmProcessingTime: 'Thời gian xử lý',
  smmAvgCompletionTime: 'Thời gian hoàn thành TB',
  smmRefillPolicy: 'Bảo hành',
  smmWarranty: 'Bảo hành',
  smmReorder: 'Đặt lại',
  smmSupportOrder: 'Hỗ trợ',
  smmPlaceOrder: 'Đặt đơn',
  smmOrderSuccess: 'Đặt đơn thành công!',
  smmOrderError: 'Lỗi khi đặt đơn',
  smmPleaseLogin: 'Vui lòng đăng nhập để đặt đơn',
  smmPleaseSelectService: 'Vui lòng chọn dịch vụ',
  smmPleaseEnterLink: 'Vui lòng nhập link',
  smmInsufficientBalance: 'Số dư không đủ. Cần {need}, hiện có {have}',
  smmTotalOrders: 'Tổng đơn',
  smmCompleted: 'Hoàn thành',
  smmProcessing: 'Đang chạy',
  smmPending: 'Chờ xử lý',
  smmCanceled: 'Đã hủy',
  smmRefunded: 'Hoàn tiền',
  smmFilterStatus: 'Lọc trạng thái',
  smmAllStatus: 'Tất cả trạng thái',
  smmStatusPending: 'Chờ xử lý',
  smmStatusProcessing: 'Đang xử lý',
  smmStatusInProgress: 'Đang chạy',
  smmStatusCompleted: 'Hoàn thành',
  smmStatusPartial: 'Một phần',
  smmStatusCanceled: 'Đã hủy',
  smmStatusRefunded: 'Đã hoàn tiền',
  smmRefreshStatus: 'Cập nhật trạng thái',
  smmStatusUpdated: 'Đã cập nhật trạng thái',
  smmRequestRefill: 'Yêu cầu bảo hành',
  smmRefill: 'Bảo hành',
  smmRefillSent: 'Đã gửi yêu cầu bảo hành',
  smmNoExternalOrderId: 'Không có ID đơn hàng bên ngoài',
  smmNoOrders: 'Chưa có đơn hàng nào',
  smmPleaseLoginToViewOrders: 'Vui lòng đăng nhập để xem đơn hàng',
  smmBulkOrderList: 'Nhập danh sách đơn hàng',
  smmBulkOrderFormat: 'Nhập mỗi đơn một dòng theo định dạng:\nservice_id|link|quantity',
  smmBulkOrderExample: 'Ví dụ:\n123|https://facebook.com/post/123|1000',
  smmValidOrders: 'Đơn hàng hợp lệ',
  smmBulkOrderSuccess: 'Đặt thành công {count} đơn',
  smmBulkOrderFailed: '{count} đơn thất bại',
  smmNoValidOrders: 'Không có đơn hàng hợp lệ',
  smmMin: 'Min',
  smmMax: 'Max',
  smmETA: 'ETA',
  smmPer1000: '/1000',
  smmNoServiceFound: 'Không tìm thấy dịch vụ nào',
  smmSearchPlaceholder: 'Tìm kiếm...',
  smmStartCount: 'Start',
  smmRemains: 'Còn',
  smmPayment: 'Thanh toán',
  smmLinkType: 'Loại liên kết',
  smmLinkSingle: 'Một',
  smmLinkMultiple: 'Nhiều',
  smmEnterMultipleUrls: 'Nhập mỗi liên kết trên một dòng',
  smmScheduleRun: 'Đặt lịch chạy',
  smmTimezone: 'Múi giờ',
  smmScheduleTime: 'Thời gian chạy',
  smmRepeatOrder: 'Đặt hàng lặp lại',
  smmRepeatOrderDesc: 'Tự động đặt lại đơn hàng sau khi đơn hàng này',
  smmRepeatCount: 'Số lần lặp lại',
  smmRepeatInterval: 'Giãn cách (phút)',
  smmEnsureBalance: 'Đảm bảo số dư của bạn đủ cho các đơn hàng sau.',
  smmServiceInfo: 'Thông tin dịch vụ',
  smmServiceId: 'ID dịch vụ',
  smmServiceName: 'Tên dịch vụ',
  smmDescription: 'Mô tả',
  smmSearchOrders: 'Tìm mã đơn, dịch vụ, link...',
  smmService: 'Dịch vụ',
  smmAmount: 'Số tiền',
  smmActions: 'Thao tác',
  smmRefresh: 'Làm mới',
  smmCreatedAt: 'Thời gian tạo',
  smmCompletedAt: 'Hoàn thành',
  // Support/Ticket additional keys
  ticketSubjectPlaceholder: 'Nhập tiêu đề yêu cầu...',
  ticketCategory: 'Danh mục',
  ticketContent: 'Nội dung',
  ticketContentPlaceholder: 'Mô tả chi tiết vấn đề của bạn...',
  noTicketsYet: 'Chưa có yêu cầu hỗ trợ',
  createFirstTicketDesc: 'Tạo yêu cầu đầu tiên để nhận hỗ trợ từ đội ngũ của chúng tôi',
  createFirstTicket: 'Tạo yêu cầu đầu tiên',
  statusOpen: 'Mở',
  statusResolved: 'Đã giải quyết',
  statusClosed: 'Đã đóng',
  // Gift Card
  giftCard: 'Gift Card',
  giftCardTitle: 'Gift Card',
  giftCardLoginPrompt: 'Đăng nhập để mua và tặng Gift Card cho bạn bè',
  giftCardLoginNow: 'Đăng nhập ngay',
  giftCardForLovedOnes: 'Tặng quà cho người thân',
  giftCardDescription: 'Gửi tặng Gift Card đến bạn bè và người thân - món quà ý nghĩa cho mọi dịp',
  giftCardBalance: 'Số dư',
  giftCardPurchase: 'Mua',
  giftCardRedeem: 'Nhập mã',
  giftCardHistory: 'Lịch sử',
  giftCardCreateNew: 'Tạo Gift Card mới',
  giftCardSelectAmount: 'Chọn mệnh giá',
  giftCardEnterOtherAmount: 'Hoặc nhập số tiền khác...',
  giftCardRecipientInfo: 'Thông tin người nhận',
  giftCardRecipientEmail: 'Email người nhận *',
  giftCardRecipientName: 'Tên người nhận',
  giftCardNameOptional: 'Tên (tuỳ chọn)',
  giftCardMessage: 'Lời nhắn',
  giftCardMessagePlaceholder: 'Viết lời chúc gửi đến người nhận...',
  giftCardTotalPayment: 'Tổng thanh toán:',
  giftCardBuyAndSend: 'Mua & Gửi Gift Card',
  giftCardInsufficientBalance: 'Số dư không đủ để thực hiện giao dịch',
  giftCardEnterCode: 'Nhập mã Gift Card',
  giftCardEnterCodeDesc: 'Nhập mã để nạp tiền vào tài khoản',
  giftCardCode: 'Mã Gift Card',
  giftCardUse: 'Sử dụng Gift Card',
  giftCardSent: 'Gift Card đã gửi',
  giftCardReceived: 'Gift Card nhận được',
  giftCardUsed: 'Đã dùng',
  giftCardNotUsed: 'Chưa dùng',
  giftCardCanUse: 'Có thể dùng',
  giftCardFrom: 'Từ:',
  giftCardUseNow: 'Sử dụng ngay',
  giftCardNoSent: 'Chưa gửi gift card nào',
  giftCardNoReceived: 'Chưa nhận gift card nào',
  giftCardSelectAmountDesc: 'Chọn mệnh giá và điền thông tin người nhận',
  // New Gift Card features
  giftCardSelectTemplate: 'Chọn mẫu thiết kế',
  giftCardScheduled: 'Gửi theo lịch',
  giftCardScheduledAt: 'Ngày gửi',
  giftCardScheduledDesc: 'Gift card sẽ được gửi vào ngày bạn chọn',
  giftCardScheduledNote: 'Người nhận sẽ nhận email vào ngày này',
  giftCardShare: 'Chia sẻ Gift Card',
  giftCardShareLink: 'Link chia sẻ',
  giftCardScanQR: 'Quét mã QR để nhận',
  giftCardBulkPurchase: 'Mua số lượng lớn',
  giftCardBulkEmails: 'Email người nhận (mỗi dòng 1 email)',
  giftCardBulkEmailsPlaceholder: 'email1@example.com\nemail2@example.com\nemail3@example.com',
  giftCardBulkEmailsNote: 'Để trống nếu muốn tự gửi sau',
  giftCardBulkTotal: 'Tổng cộng',
  giftCardBulkConfirm: 'Xác nhận mua',
  giftCardAmount: 'Mệnh giá',
  giftCardQuantity: 'Số lượng',
  giftCardDiscount: 'Giảm giá',
  giftCardPromoActive: 'Khuyến mãi đang áp dụng',
  giftCardOriginalPrice: 'Giá gốc',
  giftCardFinalPrice: 'Giá sau giảm',
  giftCardCheckBalance: 'Kiểm tra số dư',
  giftCardCheckBalanceDesc: 'Nhập mã để kiểm tra số dư Gift Card',
  giftCardBalanceResult: 'Số dư còn lại',
  giftCardExpires: 'Hết hạn',
  giftCardNotifyEnabled: 'Thông báo đã bật',
  giftCardNotifyDesc: 'Bạn sẽ nhận email khi Gift Card sắp hết hạn',
  giftCardScheduledFor: 'Sẽ gửi vào',
  giftCardShareVia: 'Chia sẻ qua',
  
  // Chat
  chat: 'Tin nhắn',
  chatWith: 'Trò chuyện với',
  chatRooms: 'Cuộc trò chuyện',
  newMessage: 'Tin nhắn mới',
  noMessages: 'Chưa có tin nhắn',
  noChatRooms: 'Chưa có cuộc trò chuyện nào',
  startNewChat: 'Bắt đầu trò chuyện mới',
  sendingMessage: 'Đang gửi...',
  messageSentSuccess: 'Đã gửi tin nhắn',
  chatSettings: 'Cài đặt chat',
  chatTheme: 'Chủ đề',
  quickReaction: 'Phản ứng nhanh',
  createGroup: 'Tạo nhóm',
  addPeople: 'Thêm người',
  groupName: 'Tên nhóm',
  groupMembers: 'Thành viên nhóm',
  leaveGroup: 'Rời nhóm',
  deleteChat: 'Xóa cuộc trò chuyện',
  deleteChatConfirm: 'Bạn có chắc muốn xóa cuộc trò chuyện này?',
  onlineNow: 'Đang online',
  lastSeen: 'Hoạt động',
  customerSupport: 'Hỗ trợ khách hàng',
  chatWithAdmin: 'Chat với Admin',
  
  // Marketplace
  marketplace: 'Chợ',
  marketplaceDesc: 'Mua bán sản phẩm từ người dùng',
  seller: 'Người bán',
  buyer: 'Người mua',
  sellerDashboard: 'Quản lý Shop',
  myShop: 'Shop của tôi',
  shopName: 'Tên Shop',
  shopDescription: 'Mô tả Shop',
  shopSettings: 'Cài đặt Shop',
  registerSeller: 'Đăng ký bán hàng',
  becomeSeller: 'Trở thành người bán',
  sellerProducts: 'Sản phẩm của bạn',
  addProduct: 'Thêm sản phẩm',
  editProduct: 'Sửa sản phẩm',
  productTitle: 'Tên sản phẩm',
  productDescription: 'Mô tả sản phẩm',
  productPrice: 'Giá bán',
  productImages: 'Hình ảnh',
  productStatus: 'Trạng thái',
  productApproved: 'Đã duyệt',
  productPending: 'Chờ duyệt',
  productRejected: 'Bị từ chối',
  sellerRevenue: 'Doanh thu',
  sellerOrders: 'Đơn hàng',
  sellerReviews: 'Đánh giá',
  chatWithSeller: 'Chat với người bán',
  contactSeller: 'Liên hệ người bán',
  followShop: 'Theo dõi Shop',
  unfollowShop: 'Bỏ theo dõi',
  shopFollowers: 'Người theo dõi',
  shopProducts: 'Sản phẩm',
  shopRating: 'Đánh giá',
  
  // Seller Dashboard
  sellerOverview: 'Tổng quan',
  sellerHello: 'Xin chào',
  sellerTodayOverview: 'Đây là tổng quan hoạt động của shop hôm nay',
  sellerAddProduct: 'Thêm sản phẩm',
  sellerPendingOrders: 'đơn hàng cần giao',
  sellerDeliverSoon: 'Vui lòng giao hàng sớm nhất',
  sellerViewNow: 'Xem ngay',
  sellerBalance: 'Số dư',
  sellerHeldBalance: 'Tạm giữ',
  sellerTotalRevenue: 'Doanh thu',
  sellerProductsCount: 'Sản phẩm',
  sellerTotal: 'tổng',
  sellerSold: 'Đã bán',
  sellerQuickActions: 'Thao tác nhanh',
  sellerCreateFlashSale: 'Tạo Flash Sale',
  sellerViewMessages: 'Xem tin nhắn',
  sellerViewStats: 'Xem thống kê',
  sellerRecentOrders: 'Đơn hàng gần đây',
  sellerViewAll: 'Xem tất cả',
  sellerWaitingDelivery: 'Chờ giao',
  sellerDelivered: 'Đã giao',
  sellerCompleted: 'Hoàn tất',
  sellerLoginToContinue: 'Đăng nhập để tiếp tục',
  sellerNeedLogin: 'Bạn cần đăng nhập để quản lý cửa hàng',
  sellerOpenShop: 'Mở cửa hàng của bạn',
  sellerStartEarning: 'Bắt đầu kiếm tiền bằng cách bán tài khoản game trên nền tảng của chúng tôi',
  sellerRegisterNow: 'Đăng ký ngay',
  sellerPendingApproval: 'Đang chờ duyệt',
  sellerPendingApprovalDesc: 'Cửa hàng của bạn đang được xem xét. Chúng tôi sẽ thông báo khi được phê duyệt.',
  sellerShopSuspended: 'Cửa hàng bị tạm khóa',
  sellerRequestRejected: 'Yêu cầu bị từ chối',
  sellerContactAdmin: 'Vui lòng liên hệ admin để biết thêm chi tiết.',
  sellerViewShop: 'Xem Shop',
  sellerWaitingDeliveryCount: 'chờ giao',
  sellerManageProducts: 'Quản lý sản phẩm',
  sellerInventory: 'Quản lý kho',
  sellerCombos: 'Combo sản phẩm',
  sellerOrdersNav: 'Đơn hàng',
  sellerHandover: 'Bàn giao tài khoản',
  sellerAuctions: 'Đấu giá',
  sellerVouchers: 'Voucher',
  sellerFlashSale: 'Flash Sale',
  sellerBoostProducts: 'Ghim sản phẩm',
  sellerPosts: 'Bài viết',
  sellerWallet: 'Ví & Rút tiền',
  sellerRevenueStats: 'Thống kê doanh thu',
  sellerInsights: 'Insights',
  sellerCustomerMessages: 'Tin nhắn khách hàng',
  sellerSupportTickets: 'Ticket hỗ trợ',
  sellerAiAssistant: 'AI Trợ lý',
  sellerSettingsNav: 'Cài đặt Shop',
  sellerBranding: 'Giao diện Shop',
  sellerPolicies: 'Điều khoản',
  sellerRiskControl: 'Kiểm soát rủi ro',
  sellerBlacklist: 'Blacklist',
  sellerWebhooks: 'API & Webhooks',
  sellerNavOverview: 'Tổng quan',
  sellerNavProducts: 'Sản phẩm',
  sellerNavSales: 'Bán hàng',
  sellerNavMarketing: 'Marketing',
  sellerNavFinance: 'Tài chính',
  sellerNavSupport: 'Hỗ trợ',
  sellerNavSettings: 'Cài đặt',
  sellerNavDesign: 'Dịch vụ',
  sellerDesignServices: 'Quản lý dịch vụ',
  sellerDesignOrders: 'Đơn hàng thiết kế',
  
  // Design Order System
  designer: 'Designer',
  designerDashboard: 'Bảng điều khiển Designer',
  waitingDesignerAccept: 'Chờ designer nhận',
  designerAccepted: 'Designer đã nhận',
  designerWorking: 'Designer đang làm',
  designerSubmitted: 'Designer đã nộp',
  waitingBuyerConfirm: 'Chờ khách xác nhận',
  orderCompleted: 'Hoàn thành',
  orderCancelled: 'Đã hủy',
  orderDisputed: 'Tranh chấp',
  designOrder: 'Đơn thiết kế',
  designOrderId: 'Mã đơn thiết kế',
  chatWithDesigner: 'Chat với designer',
  contactDesigner: 'Liên hệ designer',
  designerProfile: 'Hồ sơ designer',
  designerRevisions: 'Số lần sửa',
  designerDeadline: 'Thời hạn',
  designerDelivery: 'Giao hàng',
  designerEscrow: 'Tiền tạm giữ',
  escrowInfo: 'Tiền đã được giữ và sẽ chuyển cho designer sau khi bạn xác nhận',
  releaseToDesigner: 'Chuyển cho designer',
  confirmDesignReceived: 'Xác nhận đã nhận',
  requestRevision: 'Yêu cầu sửa',
  acceptDesign: 'Chấp nhận thiết kế',
  rejectDesign: 'Từ chối thiết kế',
  designerNotes: 'Ghi chú từ designer',
  buyerNotes: 'Ghi chú từ khách',
  revisionsRemaining: 'Còn {count} lượt sửa',
  noRevisionsLeft: 'Hết lượt sửa',
  designFiles: 'File thiết kế',
  uploadDesign: 'Upload thiết kế',
  downloadDesign: 'Tải thiết kế',
  designPreview: 'Xem trước',
  designVersion: 'Phiên bản',
  designLatestVersion: 'Phiên bản mới nhất',
  designPreviousVersions: 'Phiên bản trước',
  designerRating: 'Đánh giá designer',
  rateDesigner: 'Đánh giá designer',
  designerStats: 'Thống kê',
  totalDesignOrders: 'Tổng đơn thiết kế',
  completedDesigns: 'Hoàn thành',
  pendingDesigns: 'Đang xử lý',
  designRevenue: 'Doanh thu thiết kế',
  rushDelivery: 'Giao nhanh',
  rushDeliveryFee: 'Phí giao nhanh',
  ndaProtection: 'Bảo mật NDA',
  ndaEnabled: 'Đã bật NDA',
  ndaDescription: 'Thông tin đơn hàng được bảo mật theo thỏa thuận NDA',
  designCategory: 'Danh mục thiết kế',
  designStyle: 'Phong cách',
  designRequirements: 'Yêu cầu thiết kế',
  designBrief: 'Brief thiết kế',
  attachments: 'Tệp đính kèm',
  referenceImages: 'Ảnh tham khảo',
  
  // Auction
  auction: 'Đấu giá',
  auctions: 'Phiên đấu giá',
  auctionDetails: 'Chi tiết đấu giá',
  currentBid: 'Giá hiện tại',
  startingPrice: 'Giá khởi điểm',
  bidNow: 'Đấu giá ngay',
  placeBid: 'Đặt giá',
  yourBid: 'Giá của bạn',
  minBid: 'Giá tối thiểu',
  bidAmount: 'Số tiền đấu giá',
  bidHistory: 'Lịch sử đấu giá',
  highestBidder: 'Người trả giá cao nhất',
  auctionEndsIn: 'Kết thúc sau',
  auctionEnded: 'Đã kết thúc',
  auctionWon: 'Bạn thắng!',
  auctionLost: 'Đã kết thúc',
  bidSuccess: 'Đã đặt giá thành công',
  bidError: 'Không thể đặt giá',
  outbid: 'Đã bị vượt giá',
  watchAuction: 'Theo dõi đấu giá',
  unwatchAuction: 'Bỏ theo dõi',
  buyNowPrice: 'Giá mua ngay',
  reservePrice: 'Giá đặt trước',
  auctionType: 'Loại đấu giá',
  standardAuction: 'Đấu giá thường',
  dutchAuction: 'Đấu giá Hà Lan',
  sealedBid: 'Đấu giá kín',
  
  // Stories
  stories: 'Tin',
  createStory: 'Tạo tin',
  viewStory: 'Xem tin',
  storyExpired: 'Tin đã hết hạn',
  addToStory: 'Thêm vào tin',
  storyViews: 'Lượt xem',
  
  // Social/Newsfeed
  newsfeed: 'Bảng tin',
  createPost: 'Tạo bài viết',
  whatsOnYourMind: 'Bạn đang nghĩ gì?',
  postContent: 'Nội dung bài viết',
  addPhoto: 'Thêm ảnh',
  like: 'Thích',
  unlike: 'Bỏ thích',
  comment: 'Bình luận',
  comments: 'Bình luận',
  share: 'Chia sẻ',
  sharePost: 'Chia sẻ bài viết',
  writeComment: 'Viết bình luận...',
  noPostsYet: 'Chưa có bài viết nào',
  postSuccess: 'Đã đăng bài viết',
  postError: 'Không thể đăng bài viết',
  deletePost: 'Xóa bài viết',
  editPost: 'Sửa bài viết',
  reportPost: 'Báo cáo bài viết',
  
  // Friends
  friends: 'Bạn bè',
  friendRequests: 'Lời mời kết bạn',
  addFriend: 'Kết bạn',
  unfriend: 'Hủy kết bạn',
  acceptRequest: 'Chấp nhận',
  declineRequest: 'Từ chối',
  pendingRequest: 'Đã gửi lời mời',
  mutualFriends: 'Bạn chung',
  noFriendsYet: 'Chưa có bạn bè',
  searchFriends: 'Tìm kiếm bạn bè',
  friendRequestSent: 'Đã gửi lời mời kết bạn',
  friendRequestAccepted: 'Đã chấp nhận lời mời kết bạn',
  
  // Notifications
  markAllRead: 'Đánh dấu đã đọc',
  clearAll: 'Xóa tất cả',
  noNotifications: 'Không có thông báo mới',
  notificationSettings: 'Cài đặt thông báo',
  pushNotifications: 'Thông báo đẩy',
  emailNotifications: 'Thông báo email',
  
  // Daily Check-in
  dailyCheckin: 'Điểm danh hàng ngày',
  checkinSuccess: 'Điểm danh thành công!',
  alreadyCheckedIn: 'Bạn đã điểm danh hôm nay',
  streakDays: 'ngày liên tiếp',
  checkinReward: 'Phần thưởng',
  pointsEarned: 'điểm',
  
  // Points & Rewards
  points: 'Điểm',
  myPoints: 'Điểm của tôi',
  earnPoints: 'Kiếm điểm',
  spendPoints: 'Đổi điểm',
  pointsBalance: 'Số dư điểm',
  rewardCatalog: 'Danh mục phần thưởng',
  redeemNow: 'Đổi ngay',
  pointsRequired: 'Điểm cần',
  redeemSuccess: 'Đổi thưởng thành công!',
  notEnoughPointsReward: 'Không đủ điểm',
  
  // Events
  activeEvents: 'Sự kiện đang diễn ra',
  upcomingEvents: 'Sự kiện sắp tới',
  eventDetails: 'Chi tiết sự kiện',
  eventEndsIn: 'Kết thúc sau',
  spinWheel: 'Vòng quay may mắn',
  spin: 'Quay',
  spinsRemaining: 'lượt quay còn lại',
  congratulations: 'Chúc mừng!',
  youWon: 'Bạn đã trúng',
  tryAgain: 'Thử lại',
  
  // Admin Email
  bulkEmail: 'Gửi email hàng loạt',
  emailTemplates: 'Mẫu email',
  emailLogs: 'Lịch sử gửi email',
  selectTemplate: 'Chọn mẫu',
  emailSubject: 'Tiêu đề',
  emailContent: 'Nội dung',
  sendEmail: 'Gửi email',
  emailSent: 'Đã gửi email',
  emailFailed: 'Gửi email thất bại',
  
  // Common UI
  loadMore: 'Tải thêm',
  showLess: 'Thu gọn',
  seeAll: 'Xem tất cả',
  selectAll: 'Chọn tất cả',
  deselectAll: 'Bỏ chọn tất cả',
  selected: 'Đã chọn',
  optional: 'Tùy chọn',
  required: 'Bắt buộc',
  enabled: 'Bật',
  disabled: 'Tắt',
  active: 'Hoạt động',
  inactive: 'Không hoạt động',
  verified: 'Đã xác minh',
  unverified: 'Chưa xác minh',
  default: 'Mặc định',
  custom: 'Tùy chỉnh',
  preview: 'Xem trước',
  download: 'Tải xuống',
  upload: 'Tải lên',
  uploadImage: 'Tải ảnh lên',
  dragDropImage: 'Kéo thả hoặc click để chọn ảnh',
  maxImageSize: 'Kích thước tối đa',
  supportedFormats: 'Định dạng hỗ trợ',
  
  // Time/Date
  now: 'Bây giờ',
  ago: 'trước',
  in: 'trong',
  days: 'ngày',
  hours: 'giờ',
  minutes: 'phút',
  seconds: 'giây',
  
  // Misc
  comingSoon: 'Sắp ra mắt',
  underMaintenance: 'Đang bảo trì',
  pageNotFound: 'Trang không tồn tại',
  accessDenied: 'Truy cập bị từ chối',
  sessionExpired: 'Phiên đăng nhập đã hết hạn',
  tryAgainLater: 'Vui lòng thử lại sau',
  contactSupport: 'Liên hệ hỗ trợ',
  
  // Header/Menu specific
  personalPage: 'Trang cá nhân',
  manageShop: 'Quản lý Shop',
  user: 'Người dùng',
  more: 'Thêm',
  shop: 'Cửa hàng',
  services: 'Dịch vụ',
  serviceList: 'Danh sách dịch vụ',
  placeOrder: 'Đặt đơn',
  bulkOrder: 'Đặt đơn số lượng lớn',
  smmOrdersMenu: 'Đơn hàng SMM',
  smmServicesMenu: 'SMM',
  other: 'Khác',
  apiDocs: 'Tài liệu API',
  messages: 'Tin nhắn',
  favorites: 'Yêu thích',
  vietnamese: 'Tiếng Việt',
  english: 'English',
  auctionCount: 'Đấu giá ({count})',
  switchedToVietnamese: 'Đã chuyển sang Tiếng Việt',
  switchedToEnglish: 'Switched to English',
  
  // Item Shop & Prime Boost
  itemShop: 'Cửa hàng',
  itemShopDesc: 'Khám phá các vật phẩm độc quyền',
  primeBoost: 'Prime Boost',
  primeBoostDesc: 'Nâng cấp tài khoản với đặc quyền Prime',
  avatarFramesShop: 'Khung Avatar',
  avatarFramesShopDesc: 'Trang trí avatar của bạn',
  nameColors: 'Màu tên',
  nameColorsDesc: 'Nổi bật với màu tên độc đáo',
  specialEffects: 'Hiệu ứng đặc biệt',
  specialEffectsDesc: 'Thêm hiệu ứng cho tài khoản',
  primePrice: 'Giá Prime',
  originalPriceLabel: 'Giá gốc',
  primePriceLabel: 'Giá Prime',
  primeMember: 'Thành viên Prime',
  getPrime: 'Nâng cấp Prime',
  primeDiscount: 'Giảm giá Prime',
  primeExclusive: 'Độc quyền Prime',
  primeBenefits: 'Quyền lợi Prime',
  primeActive: 'Prime đang hoạt động',
  primeExpires: 'Prime hết hạn',
  primeExpired: 'Prime đã hết hạn',
  renewPrime: 'Gia hạn Prime',
  upgradeToPrime: 'Nâng cấp lên Prime',
  loginToExplore: 'Đăng nhập để khám phá các vật phẩm độc quyền',
  giftNow: 'Tặng ngay',
  buyForSelf: 'Mua cho mình',
  change: 'Đổi',
  searchUsers: 'Tìm kiếm người dùng...',
  effects: 'Hiệu ứng',
  
  // Gifting
  giftItem: 'Tặng quà',
  giftTo: 'Tặng cho',
  giftToFriend: 'Tặng cho bạn bè',
  giftMessage: 'Lời nhắn',
  giftMessagePlaceholder: 'Nhập lời nhắn (tùy chọn)',
  sendGift: 'Gửi quà',
  sendingGift: 'Đang gửi quà...',
  giftSent: 'Đã gửi quà thành công!',
  giftFailed: 'Gửi quà thất bại',
  searchUser: 'Tìm kiếm người dùng',
  searchUserPlaceholder: 'Nhập tên hoặc email...',
  selectRecipient: 'Chọn người nhận',
  noUserFound: 'Không tìm thấy người dùng',
  recipient: 'Người nhận',
  giftFrom: 'Quà từ',
  giftReceived: 'Bạn đã nhận được quà!',
  viewGift: 'Xem quà',
  giftFrame: 'Tặng khung Avatar',
  giftFrameDesc: 'Tặng khung avatar này cho bạn bè',
  recipientAlreadyOwnsFrame: 'Người này đã sở hữu khung avatar này',
  giftedTo: 'Đã tặng cho',
  giftError: 'Có lỗi xảy ra khi tặng quà',
  confirmGift: 'Xác nhận tặng',
  
  // Item purchase
  purchaseItem: 'Mua vật phẩm',
  purchaseSuccess: 'Mua thành công!',
  purchaseFailed: 'Mua thất bại',
  itemOwned: 'Đã sở hữu',
  itemEquipped: 'Đang sử dụng',
  equipItem: 'Sử dụng',
  unequipItem: 'Bỏ sử dụng',
  buyAsGift: 'Mua làm quà',
  confirmPurchase: 'Xác nhận mua',
  
  // Avatar Frame Shop (additional keys)
  avatarFrameShop: 'Cửa hàng khung Avatar',
  avatarFrameShopDesc: 'Mua và trang bị khung avatar để trang trí hồ sơ của bạn',
  framePrice: 'Giá khung',
  needPrimeBoostForFrames: 'Bạn cần có Prime Boost để mua khung avatar',
  needPrimeBoostForColors: 'Bạn cần có Prime Boost để mua màu tên',
  needPrimeBoostForEffects: 'Bạn cần có Prime Boost để mua hiệu ứng',
  needPrimeBoostPrefix: 'Bạn cần',
  needPrimeBoostSuffixFrames: 'để mua khung avatar',
  needPrimeBoostSuffixColors: 'để mua màu tên',
  needPrimeBoostSuffixEffects: 'để mua hiệu ứng',
  
  // Admin translations
  adminTranslations: 'Quản lý bản dịch',
  translationsDesc: 'Quản lý các bản dịch ngôn ngữ',
  sourceText: 'Văn bản gốc',
  translatedText: 'Văn bản dịch',
  targetLanguage: 'Ngôn ngữ đích',
  addTranslation: 'Thêm bản dịch',
  editTranslation: 'Sửa bản dịch',
  deleteTranslation: 'Xóa bản dịch',
  translationUpdated: 'Cập nhật bản dịch thành công',
  translationDeleted: 'Xóa bản dịch thành công',
  translationAdded: 'Thêm bản dịch thành công',
  
  // Admin Prime Boost
  adminPrimeBoost: 'Quản lý Prime Boost',
  primePlans: 'Gói Prime',
  primePlanName: 'Tên gói',
  primePlanDuration: 'Thời hạn (ngày)',
  primePlanPrice: 'Giá gói',
  addPlan: 'Thêm gói',
  editPlan: 'Sửa gói',
  deletePlan: 'Xóa gói',
  planActive: 'Kích hoạt',
  planInactive: 'Tắt',
  nameColorManagement: 'Quản lý màu tên',
  effectsManagement: 'Quản lý hiệu ứng',
  benefitsManagement: 'Quản lý quyền lợi',
  colorName: 'Tên màu',
  colorValue: 'Giá trị màu',
  colorGradient: 'Gradient',
  effectName: 'Tên hiệu ứng',
  effectType: 'Loại hiệu ứng',
  effectConfig: 'Cấu hình',
  benefitKey: 'Mã quyền lợi',
  benefitName: 'Tên quyền lợi',
  benefitValue: 'Giá trị',
  
  // Seller Features
  webhooks: 'Webhooks',
  webhooksDesc: 'Nhận thông báo real-time khi có sự kiện mới',
  bulkImport: 'Import hàng loạt',
  bulkImportDesc: 'Upload file CSV để thêm nhiều sản phẩm cùng lúc',
  riskControl: 'Kiểm soát rủi ro',
  riskControlDesc: 'Cài đặt để bảo vệ shop khỏi người mua có rủi ro',
  shopPolicies: 'Điều khoản & Chính sách',
  shopPoliciesDesc: 'Thiết lập điều khoản mua hàng cho shop',
  blacklist: 'Danh sách chặn',
  blacklistDesc: 'Quản lý người mua bị chặn',
  
  // Bulk Import
  downloadTemplate: 'Tải file mẫu',
  csvFormat: 'Định dạng CSV',
  importHistory: 'Lịch sử import',
  importSuccess: 'Import thành công',
  importFailed: 'Import thất bại',
  rowsProcessed: 'Đã xử lý',
  rowsSuccess: 'Thành công',
  rowsFailed: 'Thất bại',
  
  // Webhook
  webhookUrl: 'URL Webhook',
  webhookEvents: 'Sự kiện',
  webhookSecret: 'Secret key',
  testWebhook: 'Test webhook',
  webhookDeliveries: 'Lịch sử gửi',
  addWebhook: 'Thêm Webhook',
  
  // Risk Control
  minAccountAge: 'Tuổi tài khoản tối thiểu',
  requirePhoneVerified: 'Yêu cầu xác minh SĐT',
  maxDisputeRate: 'Tỷ lệ tranh chấp tối đa',
  maxConcurrentOrders: 'Số đơn đồng thời tối đa',
  blockHighRisk: 'Chặn người mua rủi ro cao',
  
  // Policies
  returnPolicy: 'Chính sách đổi trả',
  warrantyPolicy: 'Chính sách bảo hành',
  deliveryPolicy: 'Chính sách giao hàng',
  policyRequired: 'Bắt buộc đồng ý',
  acceptPolicies: 'Tôi đồng ý với điều khoản của shop',
  
  // Settings Sidebar
  accountSettings: 'Cài đặt tài khoản',
  walletDeposit: 'Nạp tiền',
  orderHistory: 'Lịch sử đơn hàng',
  myItems: 'Vật phẩm của tôi',
  securitySettings: 'Bảo mật',
  emailSettings: 'Email',
  privacySettings: 'Riêng tư',
  rewardsPoints: 'Điểm thưởng',
  achievementsTab: 'Thành tựu',
  viewAllTransactions: 'Xem tất cả giao dịch',
  
  // Avatar & Profile
  clickCameraToChangeAvatar: 'Nhấn vào biểu tượng máy ảnh để thay đổi avatar',
  avatarPreview: 'Xem trước ảnh đại diện',
  selectImage: 'Chọn ảnh',
  selectFrame: 'Chọn khung',
  noFrameOption: 'Không',
  noOwnedFrames: 'Bạn chưa sở hữu khung nào. Mua khung trong cửa hàng!',
  autoDeleteAfter: 'Tự động xóa sau',
  never: 'Không bao giờ',
  shareToFeed: 'Chia sẻ thông tin mới lên Bảng feed',
  publicVisibility: 'Công khai',
  sayAboutAvatar: 'Hãy nói gì đó về ảnh đại diện của bạn',
  primeOnlyGif: 'Chỉ thành viên Prime mới được sử dụng ảnh GIF',
  
  // Transfer Money
  transferMoney: 'Chuyển tiền',
  searchRecipient: 'Tìm người nhận',
  searchByNameOrEmail: 'Tìm theo tên hoặc email...',
  selectRecipientToTransfer: 'Chọn người nhận để chuyển tiền',
  transferAmount: 'Số tiền chuyển',
  transferMessage: 'Lời nhắn (tùy chọn)',
  transferMessagePlaceholder: 'Nhập lời nhắn cho người nhận...',
  confirmTransfer: 'Xác nhận chuyển tiền',
  transferSuccess: 'Chuyển tiền thành công!',
  transferFailed: 'Chuyển tiền thất bại',
  transferIn: 'Nhận tiền',
  transferOut: 'Chuyển tiền',
  transferFrom: 'Nhận từ',
  transferTo: 'Chuyển đến',
  
  // Transaction Types
  transactionTypeAll: 'Tất cả',
  transactionTypePurchase: 'Mua hàng',
  transactionTypeDeposit: 'Nạp tiền',
  transactionTypeRefund: 'Hoàn tiền',
  transactionTypeBonus: 'Thưởng',
  transactionTypeDeduction: 'Trừ tiền',
  transactionTypeItemPurchase: 'Mua vật phẩm',
  transactionTypeTransferIn: 'Nhận tiền',
  transactionTypeTransferOut: 'Chuyển tiền',
  
  // Admin API Changelog
  manageApiChangelog: 'Quản lý API Changelog',
  manageApiChangeHistory: 'Quản lý lịch sử thay đổi API',
  addVersion: 'Thêm phiên bản',
  totalVersions: 'Tổng phiên bản',
  latestVersion: 'Phiên bản mới nhất',
  noChangelogYet: 'Chưa có changelog nào',
  apiChangeHistory: 'Lịch sử thay đổi API',
  version: 'Phiên bản',
  title: 'Tiêu đề',
  changes: 'Thay đổi',
  releaseDate: 'Ngày phát hành',
  actions: 'Thao tác',
  addNewVersion: 'Thêm phiên bản mới',
  versionName: 'Tên phiên bản',
  shortDescriptionPlaceholder: 'Mô tả ngắn về phiên bản này...',
  changeList: 'Danh sách thay đổi',
  describeChange: 'Mô tả thay đổi...',
  createChangelog: 'Tạo changelog',
  confirmDeleteChangelog: 'Bạn có chắc muốn xóa changelog này?',
  pleaseEnterVersionAndTitle: 'Vui lòng nhập phiên bản và tiêu đề',
  pleaseAddAtLeastOneChange: 'Vui lòng thêm ít nhất một thay đổi',
  
  // Admin Translations
  manageTranslations: 'Quản lý bản dịch',
  editCachedTranslations: 'Chỉnh sửa các bản dịch đã cache từ AI',
  addNew: 'Thêm mới',
  totalTranslations: 'Tổng bản dịch',
  translationsList: 'Danh sách bản dịch',
  originalVietnamese: 'Văn bản gốc (Tiếng Việt)',
  enterVietnameseText: 'Nhập văn bản tiếng Việt...',
  enterTranslation: 'Nhập bản dịch...',
  addNewTranslation: 'Thêm bản dịch mới',
  noTranslations: 'Không có bản dịch nào',
  translation: 'Bản dịch',
  sourceVietnamese: 'Tiếng Việt (Gốc)',
  translationUpdatedSuccess: 'Đã cập nhật bản dịch',
  translationDeletedSuccess: 'Đã xóa',
  translationAddedSuccess: 'Đã thêm bản dịch',
  translationUpdateError: 'Lỗi khi cập nhật',
  translationDeleteError: 'Lỗi khi xóa',
  translationAddError: 'Lỗi khi thêm',
  confirmDeleteTranslation: 'Xóa bản dịch này?',
  fillAllFields: 'Vui lòng điền đầy đủ',
  adding: 'Đang thêm...',
  
  // Common toast messages
  loginToSendImage: 'Vui lòng đăng nhập để gửi ảnh',
  cannotSendMessage: 'Không thể gửi tin nhắn',
  postUpdated: 'Đã cập nhật bài viết!',
  cannotUpdatePost: 'Không thể cập nhật bài',
  postDeleted: 'Đã xóa bài viết!',
  cannotDeletePost: 'Không thể xóa bài',
  groupCreated: 'Tạo group thành công!',
  cannotCreateGroup: 'Không thể tạo group',
  groupUpdated: 'Cập nhật group thành công!',
  cannotUpdateGroup: 'Không thể cập nhật group',
  joinRequestSent: 'Yêu cầu tham gia đã được gửi!',
  joinedGroup: 'Đã tham gia group!',
  cannotJoinGroup: 'Không thể tham gia group',
  leftGroup: 'Đã rời khỏi group!',
  cannotLeaveGroup: 'Không thể rời group',
  roleUpdated: 'Đã cập nhật vai trò!',
  cannotUpdateRole: 'Không thể cập nhật vai trò',
  memberRemoved: 'Đã xóa thành viên!',
  paymentTimeExpired: 'Hết thời gian thanh toán',
  cannotCopy: 'Không thể sao chép',
  checkDomainSuccess: 'Đã kiểm tra thành công',
  cannotCheckDomain: 'Không thể kiểm tra domain',
  pleaseEnterDomain: 'Vui lòng nhập tên miền',
  appliedShopVoucher: 'Áp dụng mã shop thành công!',
  appliedSystemVoucher: 'Áp dụng mã hệ thống thành công!',
  cannotBuyOwnProduct: 'Bạn không thể mua sản phẩm của chính mình',
  insufficientBalanceDeposit: 'Số dư không đủ. Vui lòng nạp thêm tiền.',
  cannotAddOwnProductToCart: 'Bạn không thể thêm sản phẩm của chính mình vào giỏ hàng',
  productAlreadyInCart: 'Sản phẩm đã có trong giỏ hàng',
  
  // Auth Page
  welcomeBack: 'Chào mừng trở lại',
  createNewAccount: 'Tạo tài khoản mới',
  loginToContinueAuth: 'Đăng nhập để tiếp tục',
  signUpFreeToday: 'Đăng ký miễn phí ngay hôm nay',
  discoverDigitalWorld: 'Khám phá thế giới',
  digitalProducts: 'sản phẩm số',
  authHeroDescription: 'Hàng ngàn sản phẩm chất lượng cao đang chờ bạn. Thanh toán an toàn, nhận hàng ngay lập tức.',
  usersCount: '10,000+ người dùng',
  trustAndUse: 'tin tưởng sử dụng',
  checkYourEmail: 'Kiểm tra email',
  emailConfirmationSent: 'Chúng tôi đã gửi email xác nhận đến',
  backToLogin: 'Quay lại đăng nhập',
  or: 'hoặc',
  pleaseCompleteCaptcha: 'Vui lòng hoàn thành captcha',
  captchaFailed: 'Xác thực captcha thất bại',
  bySigningUp: 'Bằng việc đăng ký, bạn đồng ý với',
  and: 'và',
  
  // Terms Page
  termsOfService: 'Điều khoản sử dụng',
  termsIntroTitle: '1. Giới thiệu',
  termsIntroContent: 'Chào mừng bạn đến với website của chúng tôi. Khi sử dụng dịch vụ, bạn đồng ý tuân thủ các điều khoản và điều kiện được nêu dưới đây. Vui lòng đọc kỹ trước khi sử dụng.',
  termsConditionsTitle: '2. Điều kiện sử dụng',
  termsConditionsContent: 'Bằng việc truy cập và sử dụng website, bạn xác nhận rằng bạn đã đủ 18 tuổi hoặc có sự đồng ý của phụ huynh/người giám hộ hợp pháp.',
  termsCondition1: 'Không sử dụng dịch vụ cho mục đích bất hợp pháp',
  termsCondition2: 'Không xâm phạm quyền sở hữu trí tuệ của người khác',
  termsCondition3: 'Không phát tán nội dung độc hại hoặc vi phạm pháp luật',
  termsCondition4: 'Bảo mật thông tin tài khoản cá nhân',
  termsAccountTitle: '3. Tài khoản người dùng',
  termsAccountContent: 'Bạn chịu trách nhiệm duy trì bảo mật tài khoản và mật khẩu của mình. Mọi hoạt động diễn ra dưới tài khoản của bạn sẽ được coi là do bạn thực hiện.',
  termsProductsTitle: '4. Sản phẩm và dịch vụ',
  termsProductsContent: 'Tất cả sản phẩm kỹ thuật số được cung cấp trên website đều có bản quyền và chỉ được sử dụng cho mục đích cá nhân. Nghiêm cấm việc chia sẻ, bán lại hoặc phân phối lại các sản phẩm đã mua.',
  termsPaymentTitle: '5. Thanh toán và hoàn tiền',
  termsPaymentContent: 'Thanh toán được xử lý qua các cổng thanh toán an toàn. Chính sách hoàn tiền áp dụng theo từng loại sản phẩm và được nêu rõ trong mô tả sản phẩm.',
  termsLiabilityTitle: '6. Giới hạn trách nhiệm',
  termsLiabilityContent: 'Chúng tôi không chịu trách nhiệm cho bất kỳ thiệt hại trực tiếp hoặc gián tiếp nào phát sinh từ việc sử dụng dịch vụ, ngoại trừ những trường hợp được pháp luật quy định.',
  termsChangesTitle: '7. Thay đổi điều khoản',
  termsChangesContent: 'Chúng tôi có quyền thay đổi các điều khoản này bất cứ lúc nào. Những thay đổi sẽ có hiệu lực ngay khi được đăng tải trên website.',
  termsContactTitle: '8. Liên hệ',
  termsContactContent: 'Nếu bạn có bất kỳ câu hỏi nào về điều khoản sử dụng, vui lòng liên hệ với chúng tôi qua email hoặc hệ thống ticket hỗ trợ.',
  
  // Privacy Policy Page
  privacyPolicy: 'Chính sách bảo mật',
  privacyIntroTitle: '1. Thu thập thông tin',
  privacyIntroContent: 'Chúng tôi thu thập thông tin cần thiết để cung cấp dịch vụ tốt nhất cho bạn. Các thông tin này bao gồm:',
  privacyCollect1: 'Thông tin tài khoản (email, tên, số điện thoại)',
  privacyCollect2: 'Thông tin giao dịch và lịch sử mua hàng',
  privacyCollect3: 'Thông tin thiết bị và địa chỉ IP',
  privacyCollect4: 'Cookie và dữ liệu sử dụng website',
  privacyUseTitle: '2. Sử dụng thông tin',
  privacyUseContent: 'Thông tin thu thập được sử dụng để:',
  privacyUse1: 'Xử lý đơn hàng và giao sản phẩm',
  privacyUse2: 'Hỗ trợ khách hàng và giải quyết vấn đề',
  privacyUse3: 'Gửi thông báo về đơn hàng và khuyến mãi',
  privacyUse4: 'Cải thiện trải nghiệm người dùng',
  privacySecurityTitle: '3. Bảo mật dữ liệu',
  privacySecurityContent: 'Chúng tôi áp dụng các biện pháp bảo mật tiên tiến để bảo vệ thông tin của bạn, bao gồm mã hóa SSL, xác thực hai lớp và giám sát liên tục.',
  privacySharingTitle: '4. Chia sẻ thông tin',
  privacySharingContent: 'Chúng tôi không bán hoặc chia sẻ thông tin cá nhân của bạn với bên thứ ba, ngoại trừ:',
  privacySharing1: 'Đối tác thanh toán để xử lý giao dịch',
  privacySharing2: 'Cơ quan pháp luật khi có yêu cầu hợp pháp',
  privacySharing3: 'Nhà cung cấp dịch vụ hỗ trợ hoạt động của website',
  privacyCookiesTitle: '5. Cookie',
  privacyCookiesContent: 'Website sử dụng cookie để cải thiện trải nghiệm của bạn. Bạn có thể quản lý cài đặt cookie trong trình duyệt của mình.',
  privacyRightsTitle: '6. Quyền của bạn',
  privacyRightsContent: 'Bạn có quyền truy cập, chỉnh sửa hoặc yêu cầu xóa thông tin cá nhân của mình. Liên hệ với chúng tôi qua email hoặc hệ thống ticket để thực hiện các yêu cầu này.',
  privacyContactTitle: '7. Liên hệ',
  privacyContactContent: 'Nếu bạn có bất kỳ câu hỏi nào về chính sách bảo mật, vui lòng liên hệ với chúng tôi qua email hoặc hệ thống ticket hỗ trợ.',
};

// English translations - no API call needed
const enTranslations: Record<string, string> = {
  // Navigation
  home: 'Home',
  products: 'Products',
  cart: 'Cart',
  login: 'Login',
  logout: 'Logout',
  profile: 'Account',
  search: 'Search',
  wishlist: 'Wishlist',
  notifications: 'Notifications',
  settings: 'Settings',
  premiumAccounts: 'Premium',
  gameAccounts: 'Game Accounts',
  topUp: 'Top-up',
  more: 'More',
  shop: 'Shop',
  marketplace: 'Marketplace',
  services: 'Services',
  serviceList: 'Service List',
  placeOrder: 'Place Order',
  bulkOrder: 'Bulk Order',
  smmOrdersMenu: 'SMM Orders',
  smmServicesMenu: 'SMM Services',
  other: 'Other',
  newsfeed: 'Newsfeed',
  user: 'User',
  adminPanel: 'Admin Panel',
  apiDocs: 'API Documentation',
  messages: 'Messages',
  favorites: 'Favorites',
  vietnamese: 'Vietnamese',
  english: 'English',
  auctionCount: 'Auction ({count})',
  auction: 'Auction',
  lightMode: 'Light mode',
  darkMode: 'Dark mode',
  personalPage: 'Profile',
  manageShop: 'Manage Shop',
  switchedToVietnamese: 'Đã chuyển sang Tiếng Việt',
  switchedToEnglish: 'Switched to English',
  
  // Actions
  addToCart: 'Add to cart',
  buyNow: 'Buy now',
  viewAll: 'View all',
  viewMore: 'View more',
  viewNow: 'View now',
  collapse: 'Collapse',
  save: 'Save',
  cancel: 'Cancel',
  confirm: 'Confirm',
  delete: 'Delete',
  edit: 'Edit',
  create: 'Create',
  add: 'Add',
  apply: 'Apply',
  remove: 'Remove',
  close: 'Close',
  back: 'Back',
  next: 'Next',
  previous: 'Previous',
  submit: 'Submit',
  refresh: 'Refresh',
  copy: 'Copy',
  copied: 'Copied',
  continueShopping: 'Continue shopping',
  proceedToCheckout: 'Proceed to checkout',
  processing: 'Processing...',
  saveChanges: 'Save changes',
  saving: 'Saving...',
  changeBanner: 'Change banner',
  exploreProducts: 'Explore products',
  enter: 'Enter',
  continue: 'Continue',
  goBack: 'Go back',
  submitRegister: 'Submit registration',
  enterDashboard: 'Enter Dashboard',
  requestReward: 'Request reward',
  
  // Homepage
  featuredProducts: 'Featured Products',
  featuredProductsDesc: 'Trending products list',
  latestNews: 'Latest News',
  quickActions: 'Quick access',
  categories: 'Categories',
  gameAccountsDesc: 'Trusted game accounts, best prices',
  topUpDesc: 'Fast, reliable, best prices',
  designServices: 'Design Services',
  designServicesDesc: 'Professional design services from designers',
  viewServices: 'View services',
  addProductsInAdmin: 'Add products in Admin',
  referralCTAPrefix: 'Get',
  referralCTASuffix: 'commission for each order from friends.',
  joinNow: 'Join now',
  specialOffers: 'Special Offers',
  useCode: 'Use code',
  toGet: 'to get',
  discountAwaiting: 'Many attractive discount codes are waiting for you to explore.',
  changingLanguage: 'Changing language...',
  
  // Features
  flashSale: 'Flash Sale',
  event: 'Event',
  support: 'Support',
  news: 'News',
  referral: 'Referral',
  orderLookup: 'Order lookup',
  endsIn: 'Ends in',
  soldOut: 'Sold out',
  remaining: 'Remaining',
  viewAllProducts: 'View all {count} products',
  
  // Event Page
  noEventsYet: 'No events yet',
  noEventsRunning: 'There are no events running at the moment',
  goHome: 'Go home',
  onGoing: 'Ongoing',
  currentPoints: 'Current points',
  noSpinHistory: 'No spin history yet',
  spinResult: 'Spin result',
  pleaseLoginToSpin: 'Please login to spin',
  notEnoughPoints: 'Not enough points',
  spinError: 'Error while spinning',
  claimRewardSuccess: 'Reward claimed successfully!',
  claimReward: 'Claim reward',
  fillInfoToClaimReward: 'Please fill in the information to claim your reward:',
  confirmClaimReward: 'Confirm claim reward',
  premiumProduct: 'Premium product',
  topUpGame: 'Game top-up',
  claimed: 'Claimed',
  goToHistoryToClaimReward: 'Go to "History" tab to claim reward',
  
  // Compare Page
  noProductsToCompare: 'No products to compare',
  addProductsToCompare: 'Add products to compare from the category page',
  compareProducts: 'Compare products',
  productsCount: '{count} products',
  clearAllProducts: 'Clear all',
  allProducts: 'All Products',
  attribute: 'Attribute',
  contactForPrice: 'Contact',
  backToShopping: 'Back to shopping',
  
  // Product Pages
  searchProducts: 'Search products...',
  searchFastTopup: 'Search and top-up games quickly',
  explorePremium: 'Discover premium products and services',
  type: 'Type',
  all: 'All',
  allCategories: 'All categories',
  sort: 'Sort',
  newest: 'Newest',
  oldest: 'Oldest',
  nameAZ: 'Name A-Z',
  nameZA: 'Name Z-A',
  filters: 'Filters',
  clearFilters: 'Clear filters',
  noProductsFound: 'No products found',
  noProductsMatchFilter: 'No products match the filter',
  showingProducts: 'Showing',
  ofProducts: 'products',
  totalProducts: 'total',
  
  // Item Shop Page
  noAvatarFrames: 'No avatar frames yet',
  giftAvatarFrame: 'Gift avatar frame',
  buyAvatarFrame: 'Buy avatar frame',
  chooseGiftRecipient: 'Choose gift recipient',
  confirmBuyFrame: 'Confirm purchase this avatar frame?',
  pleaseLoginToSendImage: 'Please login to send image',
  pleaseLoginToChat: 'Please login to chat',
  
  // Avatar Frame Shop (additional keys)
  avatarFrameShop: 'Avatar Frame Shop',
  avatarFrameShopDesc: 'Buy and equip avatar frames to decorate your profile',
  framePrice: 'Frame price',
  needPrimeBoostForFrames: 'You need Prime Boost to buy avatar frames',
  needPrimeBoostForColors: 'You need Prime Boost to buy name colors',
  needPrimeBoostForEffects: 'You need Prime Boost to buy effects',
  needPrimeBoostPrefix: 'You need',
  needPrimeBoostSuffixFrames: 'to buy avatar frames',
  needPrimeBoostSuffixColors: 'to buy name colors',
  needPrimeBoostSuffixEffects: 'to buy effects',
  
  // Product
  price: 'Price',
  originalPrice: 'Original price',
  discount: 'Discount',
  inStock: 'In stock',
  outOfStock: 'Out of stock',
  description: 'Description',
  warranty: 'Warranty',
  usageGuide: 'Usage guide',
  guide: 'Guide',
  reviews: 'Reviews',
  relatedProducts: 'Related products',
  selectPackage: 'Select package',
  quantity: 'Quantity',
  sold: 'Sold',
  available: 'Available',
  package: 'Package',
  productCode: 'Product code',
  category: 'Category',
  status: 'Status',
  postedTime: 'Posted time',
  sellingPrice: 'Selling price',
  accountInfo: 'Account info',
  applyPromoCode: 'Apply promo code',
  enterDiscountCode: 'Enter discount code',
  customerBenefits: 'Customer benefits',
  instantDelivery: 'Account is delivered immediately after successful payment.',
  refundGuarantee: '100% refund guarantee if account has issues.',
  sellerSupport: 'Seller provides support and warranty during transaction.',
  recordAdvice: 'Recommended: Record video from the moment of purchase for safety and clear evidence in case of disputes!',
  recommendedProducts: 'Recommended products',
  buyAccount: 'Buy account',
  emailToReceiveAccount: 'Email to receive account',
  vipDiscountLabel: 'VIP discount',
  taxLabel: 'Tax',
  loginToPayWithBalance: 'Login to pay with balance',
  usagePeriod: 'Usage period',
  enterAdditionalInfo: 'Enter additional info',
  orderInfo: 'Order info',
  allPackagesOutOfStock: 'All packages are currently out of stock. Please come back later.',
  quickPayment: 'Quick payment',
  emailToReceive: 'Email to receive',
  productNotFound: 'Product not found',
  productMayDeleted: 'This product may have been deleted.',
  returnToHome: 'Return to home',
  addedToCart: 'Added to cart',
  pleaseSelectPackage: 'Please select a package',
  pleaseEnter: 'Please enter',
  pleaseEnterEmail: 'Please enter email to receive product',
  payWithBalanceBtn: 'Pay with balance',
  payWithPayOSBtn: 'Pay with PayOS',
  accountsRemaining: '{count} accounts remaining',
  addedToWishlistWithNotify: 'Added to wishlist with discount notification',
  pleaseLoginForNotify: 'Please login to receive notifications',
  pleaseLoginToBuy: 'Please login to purchase',
  addToWishlistFirst: 'Please add to wishlist before enabling notification',
  turnOffSaleNotify: 'Turn off sale notification',
  turnOnSaleNotify: 'Turn on notification when on sale',
  productReviews: 'Product reviews',
  productLabel: 'Product',
  outOfStockShort: 'Out',
  
  // Cart & Checkout
  emptyCart: 'Cart is empty',
  emptyCartMessage: 'You have no products in your cart. Explore our products.',
  subtotal: 'Subtotal',
  total: 'Total',
  totalPayment: 'Total payment',
  checkout: 'Checkout',
  voucherCode: 'Voucher code',
  referralCode: 'Referral code',
  paymentMethod: 'Payment method',
  balance: 'Balance',
  payWithBalance: 'Pay with balance',
  payWithPayOS: 'Pay via PayOS',
  insufficientBalance: 'Insufficient balance',
  orderSummary: 'Order summary',
  orderDetails: 'Order details',
  tax: 'Tax',
  vipDiscount: 'VIP discount',
  voucherDiscount: 'Voucher discount',
  buyerInfo: 'Buyer info',
  referralCommissionNote: 'Referrer will receive commission when order is completed',
  enterReferralCode: 'Enter referral code (if any)',
  enterVoucherCode: 'Enter voucher code',
  voucherApplied: 'Voucher applied',
  securePayment: 'Secure payment with 256-bit SSL',
  payOSDescription: 'Bank transfer, QR Pay, E-wallet',
  currentBalance: 'Current balance',
  notEnoughBalance: 'Not enough balance',
  topUpMore: 'Top up more',
  cartItemCount: 'Cart',
  needProductFirst: 'You need to add products to cart first',
  returnHome: 'Return to home',
  
  // Auth
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm password',
  fullName: 'Full name',
  signUp: 'Sign up',
  signIn: 'Sign in',
  forgotPassword: 'Forgot password?',
  orContinueWith: 'or',
  resetPassword: 'Reset password',
  sendOTP: 'Send OTP',
  verifyOTP: 'Verify OTP',
  account: 'Account',
  loginOrSignup: 'Login or sign up to continue',
  loginWithGoogle: 'Login with Google',
  loginWithDiscord: 'Login with Discord',
  loggingIn: 'Logging in...',
  signingUp: 'Signing up...',
  loginSuccess: 'Login successful',
  signupSuccess: 'Sign up successful! Logging in...',
  emailInvalid: 'Invalid email',
  passwordMinLength: 'Password must be at least 6 characters',
  fullNameMinLength: 'Full name must be at least 2 characters',
  loginToContinue: 'Login to continue',
  pleaseLoginToViewOrders: 'Please login to view your order history.',
  pleaseLoginToJoinReferral: 'Please login to join the referral program and track your commissions.',
  
  // Profile
  myOrders: 'My orders',
  myWishlist: 'My wishlist',
  security: 'Security',
  depositHistory: 'Deposit history',
  vipLevel: 'VIP level',
  totalSpent: 'Total spent',
  accountInfoProfile: 'Account info',
  personalInfo: 'Personal info',
  changePassword: 'Change password',
  twoFactorAuth: '2FA',
  loginHistory: 'Login history',
  vouchers: 'Vouchers',
  yourVouchers: 'Your vouchers',
  systemVouchers: 'System vouchers',
  availableVouchers: 'Available vouchers',
  noVouchersAvailable: 'No vouchers available',
  avatarFrames: 'Avatar frames',
  deposit: 'Deposit',
  depositToAccount: 'Deposit to account',
  selectOrEnterAmount: 'Select amount or enter custom amount',
  orEnterOtherAmount: 'Or enter other amount',
  enterAmount: 'Enter amount...',
  minimumDeposit: 'Minimum:',
  paypalNotConfigured: 'PayPal not configured. Please switch to VND or contact support.',
  depositViaPayOS: 'Deposit via PayOS',
  depositViaPayPal: 'Deposit via PayPal',
  depositViaPayPalDesc: 'Deposit via PayPal (USD)',
  depositPayPalNote: 'Amount will be converted to USD for PayPal payment',
  depositCancelled: 'Deposit cancelled',
  depositSuccess: 'Deposit successful!',
  viewDepositHistory: 'View deposit transaction history',
  noDepositYet: 'No deposit transactions yet',
  viewOrderHistory: 'View order history',
  noOrderYet: 'No orders yet',
  wishlistDescription: 'Track favorite products and get notified when on sale',
  noWishlistYet: 'No wishlist items yet',
  notifyOnDiscount: 'Notify on discount',
  updateAccountInfo: 'Update your account info',
  phone: 'Phone number',
  enterFullName: 'Enter full name...',
  enterPhone: 'Enter phone number...',
  accountBalance: 'Account balance',
  remainingToNextVip: 'Remaining',
  toReach: 'to reach',
  history: 'History',
  orders: 'Orders',
  frames: 'Frames',
  api: 'API',
  fileTooLarge: 'File too large',
  maxFileSize: 'Maximum',
  minDepositAmount: 'Minimum deposit amount',
  cannotCreatePaymentLink: 'Cannot create payment link',
  depositError: 'Error occurred while depositing',
  updateSuccess: 'Update successful',
  updateError: 'Error occurred while updating',
  logoutSuccess: 'Logged out',
  
  // Ticket & Support
  ticketNotFound: 'Ticket not found.',
  needLoginToViewTicket: 'You need to login to view ticket.',
  backToList: 'Back to list',
  ticketClosed: 'This ticket has been closed. Create a new ticket if you need more support.',
  enterMessage: 'Enter message...',
  ticketStatusOpen: 'Open',
  ticketStatusPending: 'Pending',
  ticketStatusResolved: 'Resolved',
  ticketStatusClosed: 'Closed',
  categoryGeneral: 'General',
  categoryOrder: 'Order issue',
  categoryPayment: 'Payment',
  categoryAccount: 'Account',
  categoryTechnical: 'Technical',
  categoryOther: 'Other',
  categoryLabel: 'Category',
  createdLabel: 'Created',
  
  // Shop Support
  shopSupport: 'Shop Support',
  shopSupportDesc: 'Conversations with shops on Marketplace',
  noShopTickets: 'You have no conversations with shops yet',
  
  // Support Page Tabs
  allTickets: 'All',
  systemTickets: 'System',
  shopTickets: 'Shop',
  systemLabel: 'System',
  noSystemTickets: 'No system tickets yet',
  noSystemTicketsDesc: 'Create a ticket to get support from admin team',
  createNewTicket: 'Create new ticket',
  manageSupportRequests: 'Manage your support requests',
  
  // Messages
  success: 'Success',
  error: 'Error',
  loading: 'Loading...',
  noData: 'No data',
  pleaseLogin: 'Please login',
  pleaseLoginToContinue: 'You need to login to continue checkout',
  pleaseLoginToView: 'You need to login to view cart and checkout',
  loginNow: 'Login now',
  noResults: 'No results found',
  confirmDelete: 'Are you sure you want to delete?',
  actionSuccess: 'Action successful',
  actionFailed: 'Action failed',
  paymentSuccess: 'Payment successful!',
  paymentError: 'Error occurred during payment',
  orderSuccess: 'Order successful! Redirecting to payment...',
  orderError: 'Error occurred while ordering',
  pleaseEnterVoucher: 'Please enter voucher code',
  voucherNotFound: 'Voucher not found or expired',
  voucherExpired: 'Voucher expired',
  voucherUsedUp: 'Voucher usage limit reached',
  minOrderValue: 'Minimum order value',
  voucherApplySuccess: 'Voucher applied successfully',
  pleaseLoginToPay: 'Please login to pay',
  lookupError: 'Error occurred while looking up',
  registerError: 'Error occurred while registering',
  verifySuccess: 'Verification successful',
  emailAlreadyRegistered: 'This email is already registered',
  registerSuccess: 'Registration successful! Please wait for admin approval.',
  noReferralCode: 'No referral code yet. Please contact admin.',
  emailNotApproved: 'Email not approved for the program',
  codeUpdateError: 'Cannot update code',
  codeInUse: 'This code is already in use',
  codeMinLength: 'Referral code must be at least 4 characters',
  noCreditsToRedeem: 'You have no commission to redeem',
  rewardRequestSent: 'Reward request sent. Admin will process within 24h.',
  rewardRequestError: 'Cannot send request',
  copiedReferralCode: 'Referral code copied',
  codeUpdated: 'Code updated',
  
  // Time
  today: 'Today',
  yesterday: 'Yesterday',
  thisWeek: 'This week',
  thisMonth: 'This month',
  daysAgo: 'days ago',
  hoursAgo: 'hours ago',
  minutesAgo: 'minutes ago',
  justNow: 'Just now',
  
  // Footer
  aboutUs: 'About us',
  contact: 'Contact',
  terms: 'Terms',
  privacy: 'Privacy policy',
  links: 'Links',
  supportTicket: 'Support ticket',
  hotline: 'Hotline',
  loginToUseSupport: 'Login to use support',
  loginToUseSupportDesc: 'You need to login to create support tickets and view your support history.',
  allRightsReserved: 'All rights reserved',
  platformDescription: 'Trusted digital product marketplace. Secure payment, instant delivery.',
  
  // Reviews
  writeReview: 'Write review',
  updateYourReview: 'Update your review',
  selectStars: 'Select stars',
  commentOptional: 'Comment (optional)',
  shareExperience: 'Share your experience...',
  update: 'Update',
  sendReview: 'Send review',
  reviewCount: 'reviews',
  verifiedPurchase: 'Verified purchase',
  adminReply: 'Admin reply',
  anonymous: 'Anonymous',
  noReviewsYet: 'No reviews yet. Be the first to review!',
  loginToReview: 'Login to write review',
  pleaseSelectStars: 'Please select stars',
  reviewUpdated: 'Review updated successfully',
  reviewSubmitted: 'Review submitted successfully',
  reviewError: 'Error occurred',
  submitting: 'Submitting...',
  creating: 'Creating...',
  
  // Tickets
  createTicket: 'Create ticket',
  ticketSubject: 'Subject',
  ticketDescription: 'Describe issue',
  ticketStatus: 'Status',
  reply: 'Reply',
  noTicketsYet: 'No support requests yet',
  createFirstTicketDesc: 'Create your first request to get support from our team',
  createFirstTicket: 'Create first request',
  statusOpen: 'Open',
  statusPending: 'Pending',
  statusResolved: 'Resolved',
  statusClosed: 'Closed',
  ticketSubjectPlaceholder: 'Enter request subject...',
  ticketCategory: 'Category',
  ticketContent: 'Content',
  ticketContentPlaceholder: 'Describe your issue in detail...',
  
  // Avatar & Profile
  clickCameraToChangeAvatar: 'Click the camera icon to change avatar',
  avatarPreview: 'Avatar preview',
  selectImage: 'Select image',
  selectFrame: 'Select frame',
  noFrameOption: 'None',
  noOwnedFrames: 'You don\'t own any frames. Buy frames in the shop!',
  autoDeleteAfter: 'Auto delete after',
  never: 'Never',
  shareToFeed: 'Share update to feed',
  publicVisibility: 'Public',
  sayAboutAvatar: 'Say something about your avatar',
  primeOnlyGif: 'Only Prime members can use GIF images',
  
  // Transfer Money
  transferMoney: 'Transfer Money',
  searchRecipient: 'Search recipient',
  searchByNameOrEmail: 'Search by name or email...',
  selectRecipientToTransfer: 'Select recipient to transfer',
  transferAmount: 'Transfer amount',
  transferMessage: 'Message (optional)',
  transferMessagePlaceholder: 'Enter message for recipient...',
  confirmTransfer: 'Confirm transfer',
  transferSuccess: 'Transfer successful!',
  transferFailed: 'Transfer failed',
  transferIn: 'Received',
  transferOut: 'Sent',
  transferFrom: 'Received from',
  transferTo: 'Sent to',
  
  // Transaction Types
  transactionTypeAll: 'All',
  transactionTypePurchase: 'Purchase',
  transactionTypeDeposit: 'Deposit',
  transactionTypeRefund: 'Refund',
  transactionTypeBonus: 'Bonus',
  transactionTypeDeduction: 'Deduction',
  transactionTypeItemPurchase: 'Item Purchase',
  transactionTypeTransferIn: 'Received',
  transactionTypeTransferOut: 'Sent',
  
  // Seller Dashboard
  sellerOverview: 'Overview',
  sellerHello: 'Hello',
  sellerTodayOverview: 'Here is your shop activity overview for today',
  sellerAddProduct: 'Add product',
  sellerPendingOrders: 'orders need delivery',
  sellerDeliverSoon: 'Please deliver as soon as possible',
  sellerViewNow: 'View now',
  sellerBalance: 'Balance',
  sellerHeldBalance: 'On hold',
  sellerTotalRevenue: 'Revenue',
  sellerProductsCount: 'Products',
  sellerTotal: 'total',
  sellerSold: 'Sold',
  sellerQuickActions: 'Quick actions',
  sellerCreateFlashSale: 'Create Flash Sale',
  sellerViewMessages: 'View messages',
  sellerViewStats: 'View statistics',
  sellerRecentOrders: 'Recent orders',
  sellerViewAll: 'View all',
  sellerWaitingDelivery: 'Pending',
  sellerDelivered: 'Delivered',
  sellerCompleted: 'Completed',
  sellerLoginToContinue: 'Login to continue',
  sellerNeedLogin: 'You need to login to manage your shop',
  sellerOpenShop: 'Open your shop',
  sellerStartEarning: 'Start earning by selling game accounts on our platform',
  sellerRegisterNow: 'Register now',
  sellerPendingApproval: 'Pending approval',
  sellerPendingApprovalDesc: 'Your shop is being reviewed. We will notify you when approved.',
  sellerShopSuspended: 'Shop suspended',
  sellerRequestRejected: 'Request rejected',
  sellerContactAdmin: 'Please contact admin for more details.',
  sellerViewShop: 'View Shop',
  sellerWaitingDeliveryCount: 'pending',
  sellerManageProducts: 'Manage products',
  sellerInventory: 'Inventory',
  sellerCombos: 'Product combos',
  sellerOrdersNav: 'Orders',
  sellerHandover: 'Account handover',
  sellerAuctions: 'Auctions',
  sellerVouchers: 'Vouchers',
  sellerFlashSale: 'Flash Sale',
  sellerBoostProducts: 'Boost products',
  sellerPosts: 'Posts',
  sellerWallet: 'Wallet & Withdraw',
  sellerRevenueStats: 'Revenue statistics',
  sellerInsights: 'Insights',
  sellerCustomerMessages: 'Customer messages',
  sellerSupportTickets: 'Support tickets',
  sellerAiAssistant: 'AI Assistant',
  sellerSettingsNav: 'Shop settings',
  sellerBranding: 'Shop appearance',
  sellerPolicies: 'Policies',
  sellerRiskControl: 'Risk control',
  sellerBlacklist: 'Blacklist',
  sellerWebhooks: 'API & Webhooks',
  sellerNavOverview: 'Overview',
  sellerNavProducts: 'Products',
  sellerNavSales: 'Sales',
  sellerNavMarketing: 'Marketing',
  sellerNavFinance: 'Finance',
  sellerNavSupport: 'Support',
  sellerNavSettings: 'Settings',
  sellerNavDesign: 'Services',
  sellerDesignServices: 'Manage Services',
  sellerDesignOrders: 'Design Orders',
  
  // Design Order System
  designer: 'Designer',
  designerDashboard: 'Designer Dashboard',
  waitingDesignerAccept: 'Waiting for designer',
  designerAccepted: 'Designer accepted',
  designerWorking: 'Designer working',
  designerSubmitted: 'Designer submitted',
  waitingBuyerConfirm: 'Waiting for confirmation',
  orderCompleted: 'Completed',
  orderCancelled: 'Cancelled',
  orderDisputed: 'Disputed',
  designOrder: 'Design order',
  designOrderId: 'Design order ID',
  chatWithDesigner: 'Chat with designer',
  contactDesigner: 'Contact designer',
  designerProfile: 'Designer profile',
  designerRevisions: 'Revisions',
  designerDeadline: 'Deadline',
  designerDelivery: 'Delivery',
  designerEscrow: 'Escrow',
  escrowInfo: 'Funds are held and will be released to designer after confirmation',
  releaseToDesigner: 'Release to designer',
  confirmDesignReceived: 'Confirm received',
  requestRevision: 'Request revision',
  acceptDesign: 'Accept design',
  rejectDesign: 'Reject design',
  designerNotes: 'Designer notes',
  buyerNotes: 'Buyer notes',
  revisionsRemaining: '{count} revisions remaining',
  noRevisionsLeft: 'No revisions left',
  designFiles: 'Design files',
  uploadDesign: 'Upload design',
  downloadDesign: 'Download design',
  designPreview: 'Preview',
  designVersion: 'Version',
  designLatestVersion: 'Latest version',
  designPreviousVersions: 'Previous versions',
  designerRating: 'Designer rating',
  rateDesigner: 'Rate designer',
  designerStats: 'Statistics',
  totalDesignOrders: 'Total design orders',
  completedDesigns: 'Completed',
  pendingDesigns: 'In progress',
  designRevenue: 'Design revenue',
  rushDelivery: 'Rush delivery',
  rushDeliveryFee: 'Rush delivery fee',
  ndaProtection: 'NDA Protection',
  ndaEnabled: 'NDA enabled',
  ndaDescription: 'Order information is protected under NDA agreement',
  designCategory: 'Design category',
  designStyle: 'Style',
  designRequirements: 'Design requirements',
  designBrief: 'Design brief',
  attachments: 'Attachments',
  referenceImages: 'Reference images',
  
  // Item Shop extras
  loginToExplore: 'Login to explore exclusive items',
  giftNow: 'Gift now',
  buyForSelf: 'Buy for myself',
  change: 'Change',
  searchUsers: 'Search users...',
  effects: 'Effects',
  giftFrame: 'Gift Avatar Frame',
  giftFrameDesc: 'Gift this avatar frame to a friend',
  recipientAlreadyOwnsFrame: 'This person already owns this avatar frame',
  giftedTo: 'Gifted to',
  giftError: 'An error occurred while gifting',
  confirmGift: 'Confirm Gift',
  
  // Auth Page
  welcomeBack: 'Welcome back',
  createNewAccount: 'Create new account',
  loginToContinueAuth: 'Login to continue',
  signUpFreeToday: 'Sign up free today',
  discoverDigitalWorld: 'Discover the world of',
  digitalProducts: 'digital products',
  authHeroDescription: 'Thousands of high-quality products await you. Secure payment, instant delivery.',
  usersCount: '10,000+ users',
  trustAndUse: 'trust and use',
  checkYourEmail: 'Check your email',
  emailConfirmationSent: 'We have sent a confirmation email to',
  backToLogin: 'Back to login',
  or: 'or',
  pleaseCompleteCaptcha: 'Please complete captcha',
  captchaFailed: 'Captcha verification failed',
  bySigningUp: 'By signing up, you agree to the',
  and: 'and',
  
  // Terms Page
  termsOfService: 'Terms of Service',
  termsIntroTitle: '1. Introduction',
  termsIntroContent: 'Welcome to our website. By using our services, you agree to comply with the terms and conditions stated below. Please read carefully before using.',
  termsConditionsTitle: '2. Terms of Use',
  termsConditionsContent: 'By accessing and using the website, you confirm that you are at least 18 years old or have the consent of a parent/legal guardian.',
  termsCondition1: 'Do not use the service for illegal purposes',
  termsCondition2: 'Do not infringe on intellectual property rights of others',
  termsCondition3: 'Do not distribute harmful or illegal content',
  termsCondition4: 'Keep personal account information secure',
  termsAccountTitle: '3. User Account',
  termsAccountContent: 'You are responsible for maintaining the security of your account and password. All activities under your account will be considered as performed by you.',
  termsProductsTitle: '4. Products and Services',
  termsProductsContent: 'All digital products provided on the website are copyrighted and may only be used for personal purposes. Sharing, reselling, or redistributing purchased products is strictly prohibited.',
  termsPaymentTitle: '5. Payment and Refunds',
  termsPaymentContent: 'Payments are processed through secure payment gateways. Refund policy applies according to each product type and is clearly stated in the product description.',
  termsLiabilityTitle: '6. Limitation of Liability',
  termsLiabilityContent: 'We are not responsible for any direct or indirect damages arising from the use of the service, except as required by law.',
  termsChangesTitle: '7. Changes to Terms',
  termsChangesContent: 'We reserve the right to change these terms at any time. Changes will take effect immediately upon posting on the website.',
  termsContactTitle: '8. Contact',
  termsContactContent: 'If you have any questions about the terms of use, please contact us via email or the support ticket system.',
  
  // Privacy Policy Page
  privacyPolicy: 'Privacy Policy',
  privacyIntroTitle: '1. Information Collection',
  privacyIntroContent: 'We collect necessary information to provide you with the best service. This information includes:',
  privacyCollect1: 'Account information (email, name, phone number)',
  privacyCollect2: 'Transaction information and purchase history',
  privacyCollect3: 'Device information and IP address',
  privacyCollect4: 'Cookies and website usage data',
  privacyUseTitle: '2. Use of Information',
  privacyUseContent: 'Collected information is used to:',
  privacyUse1: 'Process orders and deliver products',
  privacyUse2: 'Customer support and problem resolution',
  privacyUse3: 'Send order notifications and promotions',
  privacyUse4: 'Improve user experience',
  privacySecurityTitle: '3. Data Security',
  privacySecurityContent: 'We apply advanced security measures to protect your information, including SSL encryption, two-factor authentication, and continuous monitoring.',
  privacySharingTitle: '4. Information Sharing',
  privacySharingContent: 'We do not sell or share your personal information with third parties, except:',
  privacySharing1: 'Payment partners for transaction processing',
  privacySharing2: 'Legal authorities when legally required',
  privacySharing3: 'Service providers supporting website operations',
  privacyCookiesTitle: '5. Cookies',
  privacyCookiesContent: 'The website uses cookies to improve your experience. You can manage cookie settings in your browser.',
  privacyRightsTitle: '6. Your Rights',
  privacyRightsContent: 'You have the right to access, edit, or request deletion of your personal information. Contact us via email or ticket system to make these requests.',
  privacyContactTitle: '7. Contact',
  privacyContactContent: 'If you have any questions about the privacy policy, please contact us via email or the support ticket system.',
};

// Global translation cache - pre-populate with both languages
const translationCache: Record<string, Record<string, string>> = {
  vi: { ...viTranslations },
  en: { ...enTranslations },
};

const pendingTranslations: Record<string, Promise<Record<string, string>>> = {};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check URL param first
    const urlParams = new URLSearchParams(window.location.search);
    const urlLang = urlParams.get('lang') as Language;
    if (urlLang === 'vi' || urlLang === 'en') {
      localStorage.setItem('language', urlLang);
      return urlLang;
    }
    const saved = localStorage.getItem('language') as Language;
    return (saved === 'vi' || saved === 'en') ? saved : 'vi';
  });
  const [translations, setTranslations] = useState<Record<string, string>>(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved === 'en' && translationCache['en'] && Object.keys(translationCache['en']).length > 0) {
      return translationCache['en'];
    }
    return viTranslations;
  });
  const [isTranslating, setIsTranslating] = useState(false);
  const hasUserChangedLanguage = useRef(false);

  // Load translations when language changes
  useEffect(() => {
    const loadTranslations = async () => {
      const shouldShowToast = hasUserChangedLanguage.current;
      
      if (language === 'vi') {
        setTranslations(viTranslations);
        if (shouldShowToast) {
          toast.success(viTranslations.switchedToVietnamese);
          hasUserChangedLanguage.current = false;
        }
        return;
      }

      // Check cache first - update immediately if available
      if (translationCache[language] && Object.keys(translationCache[language]).length > 0) {
        setTranslations(translationCache[language]);
        if (shouldShowToast) {
          toast.success('Switched to English');
          hasUserChangedLanguage.current = false;
        }
        return;
      }

      setIsTranslating(true);
      const toastId = toast.loading('Translating...');
      
      try {
        const textsToTranslate = Object.values(viTranslations);
        const keys = Object.keys(viTranslations);
        
        const { data, error } = await supabase.functions.invoke('translate', {
          body: { 
            texts: textsToTranslate, 
            targetLang: language, 
            sourceLang: 'vi' 
          }
        });

        if (error) {
          console.error('Translation error:', error);
          toast.dismiss(toastId);
          toast.error('Translation failed');
          return;
        }

        const translatedTexts = data?.translations || {};
        const newTranslations: Record<string, string> = {};
        
        keys.forEach((key) => {
          const originalText = viTranslations[key];
          newTranslations[key] = translatedTexts[originalText] || originalText;
        });

        translationCache[language] = newTranslations;
        setTranslations(newTranslations);
        toast.dismiss(toastId);
        if (shouldShowToast) {
          toast.success('Switched to English');
          hasUserChangedLanguage.current = false;
        }
      } catch (error) {
        console.error('Failed to load translations:', error);
        toast.dismiss(toastId);
        toast.error('Translation failed');
      } finally {
        setIsTranslating(false);
      }
    };

    loadTranslations();
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    if (lang === language) return;
    hasUserChangedLanguage.current = true;
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    
    // Update URL with lang param
    const url = new URL(window.location.href);
    url.searchParams.set('lang', lang);
    window.history.replaceState({}, '', url.toString());
  }, [language]);

  const t = useCallback((key: string): string => {
    return translations[key] || viTranslations[key] || key;
  }, [translations]);

  const translateText = useCallback(async (text: string): Promise<string> => {
    if (language === 'vi' || !text) return text;

    const cacheKey = `vi-${language}`;
    if (!translationCache[cacheKey]) {
      translationCache[cacheKey] = {};
    }

    // Check cache
    if (translationCache[cacheKey][text]) {
      return translationCache[cacheKey][text];
    }

    try {
      const { data, error } = await supabase.functions.invoke('translate', {
        body: { 
          texts: [text], 
          targetLang: language, 
          sourceLang: 'vi' 
        }
      });

      if (error) {
        console.error('Translation error:', error);
        return text;
      }

      const translated = data?.translations?.[text] || text;
      translationCache[cacheKey][text] = translated;
      return translated;
    } catch (error) {
      console.error('Translation failed:', error);
      return text;
    }
  }, [language]);

  const translateBatch = useCallback(async (texts: string[]): Promise<Record<string, string>> => {
    if (language === 'vi' || texts.length === 0) {
      const result: Record<string, string> = {};
      texts.forEach(text => { result[text] = text; });
      return result;
    }

    const cacheKey = `vi-${language}`;
    if (!translationCache[cacheKey]) {
      translationCache[cacheKey] = {};
    }

    // Find uncached texts
    const uncached = texts.filter(text => !translationCache[cacheKey][text]);
    
    if (uncached.length === 0) {
      const result: Record<string, string> = {};
      texts.forEach(text => { result[text] = translationCache[cacheKey][text]; });
      return result;
    }

    // Check for pending request
    const requestKey = `${cacheKey}:${uncached.sort().join('|').slice(0, 100)}`;
    if (pendingTranslations[requestKey]) {
      await pendingTranslations[requestKey];
      const result: Record<string, string> = {};
      texts.forEach(text => { result[text] = translationCache[cacheKey][text] || text; });
      return result;
    }

    const promise = (async () => {
      try {
        const { data, error } = await supabase.functions.invoke('translate', {
          body: { 
            texts: uncached, 
            targetLang: language, 
            sourceLang: 'vi' 
          }
        });

        if (error) {
          console.error('Translation error:', error);
          return {};
        }

        const translations = data?.translations || {};
        Object.entries(translations).forEach(([key, value]) => {
          translationCache[cacheKey][key] = value as string;
        });

        return translations;
      } finally {
        delete pendingTranslations[requestKey];
      }
    })();

    pendingTranslations[requestKey] = promise;
    await promise;

    const result: Record<string, string> = {};
    texts.forEach(text => { result[text] = translationCache[cacheKey][text] || text; });
    return result;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      translateText, 
      translateBatch,
      isTranslating 
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
